In [4]:
import pandas as pd
from pathlib import Path

In [5]:
DATA_DIR = Path('/Users/ben/Projects/ADEPT/Data')

In [13]:
eval_df = pd.read_excel(DATA_DIR / 'ADEPTselected 25records-validation.xlsx', sheet_name='ADEPTselected spp')

In [27]:
eval_df["taxon"] = eval_df["taxon"].astype("string").str.lower()

In [42]:
eval_df

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed min. length [mm],seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id
0,achillea millefolium,perennial,NaN,erect leafy,"rhizomatous, stoloniferous","stem, stolon, rhizome",0.06,0.65,"woolly, tomentose, glabrous",NaN,...,NaN,NaN,NaN,NaN,anemochory,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN
1,achillea millefolium,perennial,NaN,"erect leafy/tussock, herb, tree/shrub, erect l...","solitary plant, rhizome","stem, rhizome, trunk",0.40 m,1.00 m,"villous, villouse, glandular",NaN,...,2 mm,2 mm,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN
2,achillea millefolium,NaN,NaN,shrub,solitary plant,trunk,1 m,1 m,"pubescent, woolly, hairs absent, hairy",NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
3,achillea millefolium,perennial,NaN,"herb, scrambler, erect leafy",NaN,"stem, tap root",0.5 m,0.5 m,pubescentpinulose,spinulatepiny,...,1.5 mm,2.0 mm,NaN,NaN,NaN,NaN,NaN,NaN,bhl,2652962.0
4,alchemilla alpina,NaN,NaN,"tree/shrub, erect leafy",solitary plant,"trunk, stem",0.05 m,0.20 m,"pubescent, sericeous, hairy, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,vaccinium myrtillus,NaN,NaN,NaN,rhizomatous,rhizome,NaN,NaN,glandular,NaN,...,NaN,NaN,1.0,1.0,NaN,"2n = 24, 48",NaN,NaN,efloras.flora_of_north_america,NaN
61,vaccinium myrtillus,perennial,NaN,shrub,"solitary plant, rhizomatous",rhizome,0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,6.0,10,2n = 24,NaN,NaN,efloras.flora_of_china,NaN
62,vaccinium myrtillus,NaN,NaN,shrub,solitary plant,trunk,1.5 m [0.15],3 m [0.40],"glandular, hairy, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30218234.0
63,valeriana dioica,NaN,NaN,erect leafy,"solitary plant, rhizome","rhizome, tap root",0.11 m,0.38 m,NaN,NaN,...,2.5 mm,3 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
64,valeriana dioica,NaN,hygrophilous,"erect leafy, scrambler",NaN,"stem, tap root",0.15,0.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,33362730.0

In [23]:
eval_df.source_id.unique()

array([      nan,  2652962., 47353191.,   750379.,  1115231., 41685059.,
       22883499.,  7934755., 30046404., 11320960.,  8010221., 11836210.,
       29987781.,  8884077.,  7934510., 47370362.,  4614077., 31968879.,
       30156396., 46694846., 61885166., 58253841., 30218234., 33362730.])

In [39]:
pred_xslx = DATA_DIR / 'uk-peatland-species-traits.xlsx'

pred_df_list = []

for source, group_df in eval_df.groupby("source"):
    df = pd.read_excel(pred_xslx, sheet_name=source)

    df["taxon"] = df["taxon"].astype("string").str.lower()

    

    if source == 'bhl':

        matched_df = df.merge(
            group_df[["taxon", "source_id"]].drop_duplicates(),
            on=["taxon", "source_id"],
            how="inner"
        )

    else:

        matched_df = df[df.taxon.isin(group_df.taxon)]

    pred_df_list.append(matched_df)

In [40]:
pred_df = pd.concat(pred_df_list, ignore_index=True)

In [48]:
def get_row_key(row):
    parts = [row.taxon, row.source]
    if source_id := row.get("source_id", None):
        parts.append(str(source_id))
    
    return '|'.join(parts)


eval_df['key'] = eval_df.apply(get_row_key,  axis=1)

In [49]:
pred_df['key'] = pred_df.apply(get_row_key,  axis=1)

In [68]:
pred_df[pred_df['perennial organ'].notna()]

Empty DataFrame
Columns: [taxon, life form, habitat, habit, clonality, perennial organ, plant min. height [m], plant max. height [m], indumentum, spinescence, succulence, leaf arrangement, leaf architecture, leaf position, leaf shape, leaf apex, leaf base, leaf margin, leaf min. width [cm], leaf max. width [cm], leaf min. length [cm], leaf max. length [cm], bract colour, bracteole colour, inflorescence arrangement, inflorescence orientation, flower sex, flower architecture, flower merosity, flower symmetry, flower shape, flower colour, flower orientation, petal fusion, petal colour, petal min. width [cm], petal max. width [cm], calyx colour, calyx min. length [cm], calyx max. length [cm], corolla colour, corolla tube min. length [cm], corolla tube max. length [cm], corolla tube lipped, labellum colour, labellum min. width [cm], labellum max. width [cm], spur min. length [cm], spur max. length [cm], reproduction architecture, reproduction system, stamen number, stamen arrangement, stamenoid number, stamen min. length [cm], stamen max. length [cm], staminodium, pollen colour, carpel/ovary number, gynoecium arrangement, heterostyly, pollination, reward, fruit type, fruit structure, fruit dehiscence, fruit shape, fruit colour, seed colour, seeds per fruit min, seeds per fruit max, seeds per fruit min., seed min. width [mm], seed max. width [mm], seed min. length [mm], seed max. length [mm], seed min. diameter [mm], seed max. diameter [mm], dispersal mode, ploidy level (2n), root min. depth [cm], root max. depth [cm], source, source_id]
Index: []

[0 rows x 84 columns]

In [60]:
eval_df[eval_df.key.isin(pred_df['key'])]

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id,key
0,achillea millefolium,perennial,NaN,erect leafy,"rhizomatous, stoloniferous","stem, stolon, rhizome",0.06,0.65,"woolly, tomentose, glabrous",NaN,...,NaN,NaN,NaN,anemochory,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN,achillea millefolium|efloras.flora_of_north_am...
1,achillea millefolium,perennial,NaN,"erect leafy/tussock, herb, tree/shrub, erect l...","solitary plant, rhizome","stem, rhizome, trunk",0.40 m,1.00 m,"villous, villouse, glandular",NaN,...,2 mm,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN,achillea millefolium|efloras.flora_of_china|nan
2,achillea millefolium,NaN,NaN,shrub,solitary plant,trunk,1 m,1 m,"pubescent, woolly, hairs absent, hairy",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,achillea millefolium|efloras.flora_of_pakistan...
3,achillea millefolium,perennial,NaN,"herb, scrambler, erect leafy",NaN,"stem, tap root",0.5 m,0.5 m,pubescentpinulose,spinulatepiny,...,2.0 mm,NaN,NaN,NaN,NaN,NaN,NaN,bhl,2652962.0,achillea millefolium|bhl|2652962.0
4,alchemilla alpina,NaN,NaN,"tree/shrub, erect leafy",solitary plant,"trunk, stem",0.05 m,0.20 m,"pubescent, sericeous, hairy, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,alchemilla alpina|efloras.flora_of_north_ameri...
6,alchemilla filicaulis,NaN,NaN,"erect leafy, tree/shrub",solitary plant,"stem, trunk",NaN,0.4,"pubescent, hairy",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,alchemilla filicaulis|efloras.flora_of_north_a...
8,andromeda polifolia,NaN,NaN,"erect leafy, scrambler",NaN,tap root,0.05 m,0.80 m,"pubescent, hairy",NaN,...,1 mm,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN,andromeda polifolia|efloras.flora_of_north_ame...
9,andromeda polifolia,NaN,NaN,shrub,solitary plant,trunk,1,3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,1115231.0,andromeda polifolia|bhl|1115231.0
10,antennaria dioica,NaN,NaN,NaN,"stoloniferous, stolon, stolons",stolon,0.03,0.1,"papillose, glabrous, tomentose",NaN,...,NaN,NaN,NaN,NaN,2n = 28,NaN,NaN,efloras.flora_of_north_america,NaN,antennaria dioica|efloras.flora_of_north_ameri...
12,betula nana,NaN,NaN,"climber/scrambler, tree/shrub, shrub, scrambler",solitary plant,"stolon, trunk",NaN,1,pubescent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,betula nana|efloras.flora_of_north_america|nan
13,betula nana,NaN,NaN,shrub,solitary plant,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,anemochory,NaN,NaN,NaN,bhl,22883499.0,betula nana|bhl|22883499.0
14,carex capillaris,NaN,NaN,erect leafy/tussock,rhizome,rhizome,0.60 m,0.60 m,NaN,NaN,...,1.7 mm,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN,carex capillaris|efloras.flora_of_north_americ...
15,carex capillaris,perennial,terrestrial,"caespitose, tree, tussock, erect leafy/tussock","stolon, stoloniferous, stolons, rhizome","stolon, stipe, rhizome",0.15,0.4,scabrous,NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_china,NaN,carex capillaris|efloras.flora_of_china|nan
16,carex capillaris,perennial,terrestrial,"caespitose, tussock,",rhizome,rhizome,0.05,0.7,hairy,NaN,...,NaN,NaN,NaN,NaN,2n = 50,NaN,NaN,bhl,7934755.0,carex capillaris|bhl|7934755.0
17,cuscuta epithymum,NaN,NaN,erect leafy,NaN,stem,NaN,NaN,glandular,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,cuscuta epithymum|efloras.flora_of_pakistan|nan
18,drosera anglica,NaN,NaN,erect leafy,rhizome,"stem, bulb",NaN,NaN,"hairy, glandular",NaN,...,1.5 mm,NaN,NaN,NaN,2n = 40,NaN,NaN,efloras.flora_of_north_america,NaN,drosera anglica|efloras.flora_of_north_america...
20,eleocharis palustris,perennial,NaN,erect leafy/tussock,rhizome,rhizome,0.3,1.15,NaN,NaN,...,2 mm,NaN,NaN,ectzoochory,"2n = 16, 17, 36, 2n = 16, 17",NaN,NaN,efloras.flora_of_north_america,NaN,eleocharis palustris|efloras.flora_of_north_am...
21,eleocharis palustris,perennial,NaN,"scrambler, caespitose",rhizome,rhizome,0.1,1,NaN,"spiny, spinulate",...,1.4,0.8,1.0,ectzoochory,"2n = 15, 16",NaN,NaN,efloras.flora_of_china,NaN,eleocharis palustris|efloras.flora_of_china|nan
22,eleocharis palustris,perennial,NaN,"tussock, scrambler, erect leafy, caespitose",rhizome,stem,0.10 m,0.95 m,glabrous,NaN,...,2.0 mm,NaN,NaN,ectzoochory,NaN,NaN,NaN,ecoflora,NaN,eleocharis palustris|ecoflora|nan
23,eleocharis palustris,perennial,epiphyte,"erect leafy/tussock, tussock, erect leafy, cae...",rhizome,"stem, rhizome",1.00 m,1.00 m,NaN,NaN,...,NaN,NaN,NaN,ectzoochory,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,eleocharis palustris|efloras.flora_of_pakistan...
24,eleocharis palustris,perennial,NaN,"erect leafy/tussock, erect leafy, scrambler","rooting from the nodes, rhizome","rooting from the nodes, stem, rhizome",0.1,0.61,NaN,NaN,...,1.3,NaN,NaN,ectzoochory,NaN,NaN,NaN,bhl,11320960.0,eleocharis palustris|bhl|11320960.0
25,epilobium anagallidifolium,NaN,NaN,"erect leafy, herb",NaN,stem,0.05 m,0.25,"hairy, glabrous, glandular",NaN,...,1.4 mm,NaN,NaN,NaN,2n = 36,NaN,NaN,efloras.flora_of_north_america,NaN,epilobium anagallidifolium|efloras.flora_of_no...
26,epilobium anagallidifolium,perennial,NaN,"erect leafy, herb",NaN,stem,0.03,0.2,"glabrous, papillose, bristly, hairy, glandular",NaN,...,1.4 mm,NaN,NaN,NaN,2n = 36,NaN,NaN,efloras.flora_of_china,NaN,epilobium anagallidifolium|efloras.flora_of_ch...
28,erica vagans,NaN,NaN,NaN,NaN,NaN,0.30 m,0.60 m,"ciliate, hairy, glabrous",NaN,...,0.6 mm,NaN,NaN,ectzoochory,2n = 24,NaN,NaN,efloras.flora_of_north_america,NaN,erica vagans|efloras.flora_of_north_america|nan
30,galium palustre,NaN,NaN,"erect leafy, tree/shrub",solitary plant,"stem, trunk",NaN,NaN,"glabrous, scabrous, papillose",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,galium palustre|efloras.flora_of_pakistan|nan
31,galium palustre,perennial,NaN,"erect leafy,",solitary plant,"stem, trunk",0.3,0.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,29987781.0,galium palustre|bhl|29987781.0
33,hypochaeris radicata,perennial,NaN,"erect leavy, erect leafy, herb",NaN,stem,0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,ectzoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN,hypochaeris radicata|efloras.flora_of_china|nan
34,hypochaeris radicata,NaN,NaN,erect leafy,rhizomatousolitary plant,"stem, rhizome",0.15,0.5,hairy,NaN,...,7 mm,NaN,NaN,NaN,NaN,NaN,NaN,bhl,8884077.0,hypochaeris radicata|bhl|8884077.0
35,lythrum salicaria,perennial,NaN,"shrub, herb, erect leafy",solitary plant,stem,NaN,NaN,"pubescent, glabrous",NaN,...,NaN,NaN,NaN,NaN,2n = 30,NaN,NaN,efloras.flora_of_north_america,NaN,lythrum salicaria|efloras.flora_of_north_ameri...
36,lythrum salicaria,perennial,NaN,"shrub, herb, erect leafy",solitary plant,stem,0.3 m,1.5 m,"glabrescent, pubescent, scabrous, tomentose, g...",NaN,...,NaN,NaN,NaN,NaN,"2n = 30, 50, 58, 60",NaN,NaN,efloras.flora_of_china,NaN,lythrum salicaria|efloras.flora_of_china|nan
37,lythrum salicaria,perennial,NaN,NaN,NaN,NaN,0.40 m,0.70 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,lythrum salicaria|efloras.flora_of_pakistan|nan
38,lythrum salicaria,perennial,NaN,"erect leafy, herbcrambler,",rhizome,"stem, rhizome",0.7,3,hairy,NaN,...,NaN,NaN,NaN,NaN,"2n = 30, 60",NaN,NaN,bhl,7934510.0,lythrum salicaria|bhl|7934510.0
39,montia fontana,"perennial, annual",NaN,"prostrate, erect leafy",bulblet,"stem, bulb",0.01,0.3,NaN,NaN,...,1.2 mm,NaN,NaN,NaN,"2n = 20, 40",NaN,NaN,efloras.flora_of_north_america,NaN,montia fontana|efloras.flora_of_north_america|nan
41,phalaris arundinacea,perennial,NaN,"erect leafy/tussock, tree/shrub","solitary plant, rhizomatous, rhizome","trunk, rhizome",0.6,1.5,pubescent,NaN,...,NaN,NaN,NaN,anemochory,2n = 28,NaN,NaN,efloras.flora_of_china,NaN,phalaris arundinacea|efloras.flora_of_china|nan
42,phalaris arundinacea,perennial,NaN,"erect leafy/tussock, scrambler, tree/shrub","solitary plant, rhizome","trunk, rhizome",0.60 m,2.00 m,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,phalaris arundinacea|ecoflora|nan
43,phalaris arundinacea,perennial,NaN,"erect leafy/tussock, scrambler, tree/shrub","solitary plant, rhizome","trunk, rhizome",0.5,1.5,"scaley, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,phalaris arundinacea|efloras.flora_of_pakistan...
44,phalaris arundinacea,"annual, perennial",NaN,NaN,NaN,culm,NaN,NaN,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,4614077.0,phalaris arundinacea|bhl|4614077.0
45,polygala vulgaris,perennial,NaN,"erect leafy, herb, tree/shrub",solitary plant,"stem, trunk",NaN,NaN,"hairy, pubescent, glabrous",NaN,...,4.2 mm,NaN,NaN,anemochory,2n = 24,NaN,NaN,efloras.flora_of_north_america,NaN,polygala vulgaris|efloras.flora_of_north_ameri...
47,rumex acetosa,perennial,NaN,"erect leafy, tree/shrub",solitary plant,"stem, tap root, trunk",NaN,NaN,glabrous,NaN,...,2.5 mm,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_north_america,NaN,rumex acetosa|efloras.flora_of_north_america|nan
48,rumex acetosa,perennial,NaN,"erect leafy, herb, tree/shrub",solitary plant,"stem, tap root, trunk",0.4,1,NaN,NaN,...,2 mm,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN,rumex acetosa|efloras.flora_of_china|nan
49,rumex acetosa,perennial,NaN,"erect leafy, tree/shrub",solitary plant,"stem, trunk",NaN,1.2,NaN,NaN,...,2.2 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,rumex acetosa|efloras.flora_of_pakistan|nan
50,rumex acetosa,perennial,NaN,"erect leafy,",solitary plant,"stem, trunk",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30156396.0,rumex acetosa|bhl|30156396.0
51,rumex conglomeratus,perennial,NaN,"erect leafy, tree/shrub",solitary plant,"stem, trunk",0.4,1,NaN,NaN,...,1.7 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,rumex conglomeratus|efloras.flora_of_pakistan|nan
52,rumex conglomeratus,NaN,NaN,NaN,NaN,NaN,0.025 m,0.05 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,46694846.0,rumex conglomeratus|bhl|46694846.0
53,salix reticulata,perennial,terrestrial,"tree, erect leafy, tree/shrub",solitary plant,"stem, trunk, stipe",0.03 m,0.15 m,"hairy, glabrescent, glandular, glabrous, seric...",NaN,...,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN,salix reticulata|efloras.flora_of_north_americ...
55,stellaria alsine,perennial,NaN,"erect leafy, scrambler",NaN,"stem, tap root",NaN,NaN,"ciliate, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,stellaria alsine|efloras.flora_of_pakistan|nan
56,urtica dioica,perennial,NaN,"climber/scrambler, erect leafy, herb",rhizomatous,"stolon, stem, rhizome",NaN,NaN,NaN,NaN,...,1.4 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,urtica dioica|efloras.flora_of_north_america|nan
57,urtica dioica,perennial,NaN,"erect leafy/tussock, erect leafy, herb","stoloniferous, rhizome","stolon, stem, rhizome",0.4,1,hairy,NaN,...,1.4 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_china,NaN,urtica dioica|efloras.flora_of_china|nan
58,urtica dioica,perennial,NaN,"erect leafy, herb",NaN,stem,0.50 m,1.50 m,"ciliate, pubescent, hairy",NaN,...,1.5 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,urtica dioica|efloras.flora_of_pakistan|nan
60,vaccinium myrtillus,NaN,NaN,NaN,rhizomatous,rhizome,NaN,NaN,glandular,NaN,...,NaN,1.0,1.0,NaN,"2n = 24, 48",NaN,NaN,efloras.flora_of_north_america,NaN,vaccinium myrtillus|efloras.flora_of_north_ame...
61,vaccinium myrtillus,perennial,NaN,shrub,"solitary plant, rhizomatous",rhizome,0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,6.0,10,2n = 24,NaN,NaN,efloras.flora_of_china,NaN,vaccinium myrtillus|efloras.flora_of_china|nan

In [61]:
eval_df = eval_df.set_index('key')

In [64]:
eval_df.to_csv('eval.csv')

In [65]:
pred_df = pred_df.set_index('key')

In [66]:
pred_df.to_csv('pred.csv')

In [51]:
bhl_df = pd.read_excel(pred_xslx, sheet_name='bhl')

In [59]:
bhl_df[bhl_df.taxon == 'Salix reticulata']

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed min. length [mm],seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id
1607,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,804944
1608,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,"glabrous, pubescent, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,878190
1609,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,"glabrous, pubescent, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,4614417
1610,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,"glabrous, pubescent, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,18715378
1611,Salix reticulata,NaN,NaN,NaN,solitary plant,NaN,NaN,NaN,"tomentose, glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,22138604
1612,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,22883490
1613,Salix reticulata,NaN,NaN,NaN,solitary plant,NaN,NaN,NaN,"tomentose, glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,22887737
1614,Salix reticulata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"tomentose, glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,23567788
1615,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,"woolly, pubescent, hairs absent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,26150943
1616,Salix reticulata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"hairy, glabrous, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30156057
1617,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,34547185
1618,Salix reticulata,NaN,NaN,shrub,NaN,NaN,NaN,NaN,"glabrous, pubescent, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,37857403
1619,Salix reticulata,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,40002363
1620,Salix reticulata,NaN,NaN,prostrate,NaN,NaN,NaN,NaN,"glabrous, pubescent, sericeous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,43412965

In [82]:
combined = pd.read_excel(pred_xslx, sheet_name='combined')

In [76]:
combined[~combined['fruit type'].isna()]['fruit type']

29           nut
44    schizocarp
Name: fruit type, dtype: object

In [75]:


eval_df[~eval_df['fruit type'].isna()]['fruit type']

key
achillea millefolium|efloras.flora_of_north_america|nan           cypsela
achillea millefolium|efloras.flora_of_china|nan                    achene
achillea millefolium|efloras.flora_of_pakistan|nan                cypsela
achillea millefolium|bhl|2652962.0                                 achene
andromeda polifolia|efloras.flora_of_north_america|nan            capsule
antennaria dioica|efloras.flora_of_north_america|nan              cypsela
antennaria dioica|bhl|41685059.0                                   achene
betula nana|efloras.flora_of_north_america|nan                     samara
betula nana|bhl|22883499.0                                            nut
carex capillaris|efloras.flora_of_north_america|nan                achene
carex capillaris|efloras.flora_of_china|nan                      Nutlets
carex capillaris|bhl|7934755.0                                     achene
drosera anglica|efloras.flora_of_north_america|nan                capsule
eleocharis palustris|efloras.flora_of_china|nan                  Nutlets
eleocharis palustris|ecoflora|nan                                     nut
eleocharis palustris|efloras.flora_of_pakistan|nan                    nut
eleocharis palustris|bhl|11320960.0                                   nut
epilobium anagallidifolium|efloras.flora_of_north_america|nan     capsule
epilobium anagallidifolium|efloras.flora_of_china|nan             capsule
epilobium anagallidifolium|bhl|8010221.0                          capsule
erica vagans|efloras.flora_of_north_america|nan                   capsule
galium palustre|bhl|29987781.0                                   mericarp
hypochaeris rad+a33+a34|efloras.flora_of_north_america|nan        cypsela
hypochaeris radicata|efloras.flora_of_china|nan                    achene
hypochaeris radicata|bhl|8884077.0                                 achene
lythrum salicaria|efloras.flora_of_north_america|nan              capsule
lythrum salicaria|efloras.flora_of_pakistan|nan                   capsule
lythrum salicaria|bhl|7934510.0                                   capsule
montia fontana|bhl|47370362.0                                     capsule
polygala vulgaris|efloras.flora_of_north_america|nan              capsule
polygala vulgaris|bhl|31968879.0                                  capsule
rumex acetosa|efloras.flora_of_north_america|nan                   achene
rumex acetosa|efloras.flora_of_china|nan                           achene
rumex acetosa|efloras.flora_of_pakistan|nan                           nut
rumex conglomeratus|efloras.flora_of_pakistan|nan                     nut
salix reticulata|efloras.flora_of_north_america|nan               capsule
salix reticulata|bhl|61885166.0                                   capsule
stellaria alsine|efloras.flora_of_pakistan|nan                    capsule
urtica dioica|efloras.flora_of_north_america|nan                   achene
urtica dioica|efloras.flora_of_china|nan                           achene
urtica dioica|efloras.flora_of_pakistan|nan                        achene
urtica dioica|bhl|58253841.0                                       achene
vaccinium myrtillus|efloras.flora_of_north_america|nan            berries
vaccinium myrtillus|efloras.flora_of_china|nan                      berry
vaccinium myrtillus|bhl|30218234.0                                  berry
Name: fruit type, dtype: object

In [88]:
eval_df[eval_df.taxon == 'vaccinium myrtillus']

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed min. length [mm],seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id
key,,,,,,,,,,,,,,,,,,,,,
vaccinium myrtillus|efloras.flora_of_north_america|nan,vaccinium myrtillus,NaN,NaN,NaN,rhizomatous,rhizome,NaN,NaN,glandular,NaN,...,NaN,NaN,1.0,1.0,NaN,"2n = 24, 48",NaN,NaN,efloras.flora_of_north_america,NaN
vaccinium myrtillus|efloras.flora_of_china|nan,vaccinium myrtillus,perennial,NaN,shrub,"solitary plant, rhizomatous",rhizome,0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,6.0,10,2n = 24,NaN,NaN,efloras.flora_of_china,NaN
vaccinium myrtillus|bhl|30218234.0,vaccinium myrtillus,NaN,NaN,shrub,solitary plant,trunk,1.5 m [0.15],3 m [0.40],"glandular, hairy, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30218234.0

In [98]:
bhl_df = pd.read_excel(pred_xslx, sheet_name='bhl')

bhl_df[(bhl_df.taxon == 'Eleocharis palustris') & (bhl_df.source_id ==11320960)].values

array([['Eleocharis palustris', nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, 3.0, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, 'bhl', 11320960]],
      dtype=object)