In [1]:
import pandas as pd
from pathlib import Path
import re

In [2]:
DATA_DIR = Path('/Users/ben/Projects/ADEPT/Data')

OUTPUT_DIR = Path('/Users/ben/Projects/ADEPT/Code/PrePub/ADEPT/adept/data/processing/output')

In [3]:
pred_file_path = OUTPUT_DIR / 'bhl/angiosperm-set1-20.bhl.traits.xlsx'
eval_file_path = DATA_DIR / 'ADEPTselected_spp4test_2209.xlsx'
eval_file_sheet_name='set1'

In [4]:
eval_df = pd.read_excel(eval_file_path, sheet_name=eval_file_sheet_name)
# eval_df2 = pd.read_excel(DATA_DIR / 'ADEPTselected_spp3test.xlsx', sheet_name='set2')

# eval_df = pd.concat([eval_df1, eval_df2])

eval_df

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed min. length [mm],seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id
0,achillea millefolium,perennial,terrestrial,"herb, erect leafy/tussock, erect leafy","rhizome, solitary plant","rhizome, stem",0.40 m,1.00 m,"villose, glandular, bristly",NaN,...,NaN,NaN,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN
1,achillea millefolium,perennial,terrestrial,"erect leafy/tussock, erect lealfy","rhizomatous, rhizome, stoloniferous, solitary ...","rhizome, stolon",0.06,0.65,"woolly, tomentose, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN
2,alchemilla alpina,NaN,terrestrial,erect leafy,solitary plant,stem,0.05,0.2,"hairy, sericeous, glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN
3,andromeda polifolia,NaN,terrestrial,"creeping, geoxylices, scrambler",stoloniferous,"rootstock, tap root, stolon",0.05,0.8,hairy,NaN,...,1.0,1.0,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN
4,betula nana,NaN,terrestrial,"shrub, climber/scrambler, scrambler","solitary plant, stoloniferous","trunk, stolon",NaN,1 m,"glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN
5,carex capillaris,NaN,terrestrial,erect leafy/tussock,rhizomematous,rhizome,0.60 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN
6,cuscuta epithymum,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,glandular,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
7,drosera anglica,perennial,terrestrial,"erect leafy/tussock, erect lealfy","rhizome, rhizomatous",rhizome,0.1,0.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30046404.0
8,Eleocharis palustris,perennial,terrestrial,"tussock, erect leafy, scrambler","rhizomatous, stoloniferous, solitary plant","rhizome, stolons, stem",0.1,0.95,"glabrous,pubescent",NaN,...,1.2,2.0,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN
9,galium palustre,NaN,terrestrial,erect leafy,solitary plant,stem,0.5,0.8,"scabrous, glabrous, papillose",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
10,Hypochaeris radicata,perennial,terrestrial,"herb, erect leafy",solitary plant,"trunk, stem",0.15,0.6,ectzoochory,NaN,...,NaN,NaN,NaN,NaN,ectozoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN
11,lythrum salicaria,perennial,NaN,NaN,NaN,NaN,0.4,0.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
12,montia fontana,NaN,terrestrial,tussock,rhizomatous,rhizome,0.12,0.15,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,47370362.0
13,Phalaris arundinacea,perennial,terrestrial,"erect leafy/tussock, scramblar","rhizome, stoloniferous",rhizome,0.6,2,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN
14,rumex acetosa,perennial,terrestrial,"herb, geoxylices, erect leafy",solitary plant,"rootstock, stem",0.4,1,glabrous,NaN,...,1.8,2.5,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN
15,rumex conglomeratus,NaN,NaN,NaN,NaN,NaN,0.025,0.05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,46694846.0
16,salix reticulata,NaN,terrestrial,erect leafy,solitary plant,stem,0.03,0.15,"hairy, glabrescent, glandular, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN
17,stellaria alsine,perennial,terrestrial,"scrambler, geoxylices",stoloniferous,"stolon, rootstock",NaN,NaN,"glabrous, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
18,urtica dioica,perennial,terrestrial,"herb, erect leafy",solitary plant,stem,0.5,1.5,"hairy, ciliate, pubescent",NaN,...,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
19,vaccinium myrtillus,perennial,terrestrial,"shrub, erect leafy tussock","solitary plant, rhizomatous, rhizome","trunk, rhizome",0.15,0.6,NaN,NaN,...,NaN,NaN,6.0,10.0,NaN,2n = 24,NaN,NaN,efloras.flora_of_china,NaN
20,valeriana dioica,NaN,terrestrial,"geoxylices, erect leafy","solitary plant, r","Rootstock , rhizome",0.11,0.38,"pilose, glabrous",NaN,...,2.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN

In [5]:
eval_df["taxon"] = eval_df["taxon"].astype("string").str.lower()

In [6]:
eval_df

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed min. length [mm],seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id
0,achillea millefolium,perennial,terrestrial,"herb, erect leafy/tussock, erect leafy","rhizome, solitary plant","rhizome, stem",0.40 m,1.00 m,"villose, glandular, bristly",NaN,...,NaN,NaN,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN
1,achillea millefolium,perennial,terrestrial,"erect leafy/tussock, erect lealfy","rhizomatous, rhizome, stoloniferous, solitary ...","rhizome, stolon",0.06,0.65,"woolly, tomentose, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN
2,alchemilla alpina,NaN,terrestrial,erect leafy,solitary plant,stem,0.05,0.2,"hairy, sericeous, glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN
3,andromeda polifolia,NaN,terrestrial,"creeping, geoxylices, scrambler",stoloniferous,"rootstock, tap root, stolon",0.05,0.8,hairy,NaN,...,1.0,1.0,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN
4,betula nana,NaN,terrestrial,"shrub, climber/scrambler, scrambler","solitary plant, stoloniferous","trunk, stolon",NaN,1 m,"glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN
5,carex capillaris,NaN,terrestrial,erect leafy/tussock,rhizomematous,rhizome,0.60 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN
6,cuscuta epithymum,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,glandular,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
7,drosera anglica,perennial,terrestrial,"erect leafy/tussock, erect lealfy","rhizome, rhizomatous",rhizome,0.1,0.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,30046404.0
8,eleocharis palustris,perennial,terrestrial,"tussock, erect leafy, scrambler","rhizomatous, stoloniferous, solitary plant","rhizome, stolons, stem",0.1,0.95,"glabrous,pubescent",NaN,...,1.2,2.0,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN
9,galium palustre,NaN,terrestrial,erect leafy,solitary plant,stem,0.5,0.8,"scabrous, glabrous, papillose",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
10,hypochaeris radicata,perennial,terrestrial,"herb, erect leafy",solitary plant,"trunk, stem",0.15,0.6,ectzoochory,NaN,...,NaN,NaN,NaN,NaN,ectozoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN
11,lythrum salicaria,perennial,NaN,NaN,NaN,NaN,0.4,0.7,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
12,montia fontana,NaN,terrestrial,tussock,rhizomatous,rhizome,0.12,0.15,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,47370362.0
13,phalaris arundinacea,perennial,terrestrial,"erect leafy/tussock, scramblar","rhizome, stoloniferous",rhizome,0.6,2,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN
14,rumex acetosa,perennial,terrestrial,"herb, geoxylices, erect leafy",solitary plant,"rootstock, stem",0.4,1,glabrous,NaN,...,1.8,2.5,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN
15,rumex conglomeratus,NaN,NaN,NaN,NaN,NaN,0.025,0.05,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,46694846.0
16,salix reticulata,NaN,terrestrial,erect leafy,solitary plant,stem,0.03,0.15,"hairy, glabrescent, glandular, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN
17,stellaria alsine,perennial,terrestrial,"scrambler, geoxylices",stoloniferous,"stolon, rootstock",NaN,NaN,"glabrous, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
18,urtica dioica,perennial,terrestrial,"herb, erect leafy",solitary plant,stem,0.5,1.5,"hairy, ciliate, pubescent",NaN,...,1.5,1.5,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN
19,vaccinium myrtillus,perennial,terrestrial,"shrub, erect leafy tussock","solitary plant, rhizomatous, rhizome","trunk, rhizome",0.15,0.6,NaN,NaN,...,NaN,NaN,6.0,10.0,NaN,2n = 24,NaN,NaN,efloras.flora_of_china,NaN
20,valeriana dioica,NaN,terrestrial,"geoxylices, erect leafy","solitary plant, r","Rootstock , rhizome",0.11,0.38,"pilose, glabrous",NaN,...,2.5,3.0,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN

In [7]:
len(eval_df.source_id.unique())

4

In [8]:

pred_df_list = []

for source, group_df in eval_df.groupby("source"):
    df = pd.read_excel(pred_file_path, sheet_name=source)

    df["taxon"] = df["taxon"].astype("string").str.lower()


    if source == 'bhl':

        matched_df = df.merge(
            group_df[["taxon", "source_id"]].drop_duplicates(),
            on=["taxon", "source_id"],
            how="inner"
        )

    else:

        matched_df = df[df.taxon.isin(group_df.taxon)]

    pred_df_list.append(matched_df)

In [9]:
pred_df = pd.concat(pred_df_list, ignore_index=True)

In [10]:
pred_df

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id,matched_name
0,eleocharis palustris,perennial,terrestrial,"scrambler, caespitose, erect leafy, tussock","stoloniferous, rhizomatous, solitary plant","rhizome, stolon, stem",0.10 m,0.95 m,NaN,NaN,...,2.0 mm,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,NaN
1,phalaris arundinacea,perennial,terrestrial,"scrambler, erect leafy/tussock","stoloniferous, rhizome","rhizome, stolon",0.60 m,2.00 m,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
2,achillea millefolium,perennial,terrestrial,"erect leafy, erect leafy/tussock, herb","rhizome, solitary plant","rhizome, stem",0.40 m,1.00 m,"villous, glandular, villouse",NaN,...,2 mm,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN,NaN
3,hypochaeris radicata,perennial,terrestrial,"erect leavy, erect leafy, herb",solitary plant,"stem, trunk",0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,ectozoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN,NaN
4,rumex acetosa,perennial,terrestrial,"erect leafy, geoxylices, herb",solitary plant,"rootstock, stem",NaN,NaN,NaN,NaN,...,2 mm,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN,NaN
5,vaccinium myrtillus,perennial,terrestrial,"shrub, erect leafy/tussock","rhizome, rhizomatous, solitary plant","rhizome, trunk",0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,2n = 24,NaN,NaN,efloras.flora_of_china,NaN,NaN
6,achillea millefolium,perennial,terrestrial,"stoloniferous, erect leafy, erect leafy/tussock","rhizome, stoloniferous, rhizomatous, solitary ...","rhizome, stolon, stem",0.06 m,0.65 m,"glabrous, woolly, tomentose",NaN,...,NaN,NaN,NaN,anemochory,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN,NaN
7,andromeda polifolia,NaN,terrestrial,"scrambler, geoxylices",stoloniferous,"stolon, rootstock",0.05 m,0.80 m,pubescent,NaN,...,1 mm,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
8,betula nana,NaN,terrestrial,"climber/scrambler, shrub, scrambler, tree/shrub","stoloniferous, solitary plant","stolon, trunk",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
9,carex capillaris,NaN,terrestrial,erect leafy/tussock,NaN,rhizome,0.60 m,0.60 m,NaN,NaN,...,1.7 mm,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
10,salix reticulata,perennial,terrestrial,"erect leafy, tree",solitary plant,"stipe, stem",0.03 m,0.15 m,"glabrous, glabrescent, pubescent, sericeous, g...",NaN,...,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
11,cuscuta epithymum,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
12,stellaria alsine,perennial,terrestrial,"scrambler, geoxylices, erect leafy","stoloniferous, solitary plant","stolon, rootstock, stem",NaN,NaN,"glabrous, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
13,urtica dioica,perennial,terrestrial,"erect leafy, herb",solitary plant,stem,0.50 m,1.50 m,NaN,NaN,...,1.5 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
14,valeriana dioica,NaN,terrestrial,"geoxylices, erect leafy","rhizomatous, solitary plant","rhizome, rootstock",0.11 m,0.38 m,NaN,NaN,...,3 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN

In [11]:
def get_row_key(row):
    parts = [row.taxon, row.source]
    source_id = row.get("source_id")
    
    if pd.notna(source_id):   
        parts.append(str(source_id))
    
    return '|'.join(parts)


eval_df['key'] = eval_df.apply(get_row_key,  axis=1)

In [12]:
pred_df['key'] = pred_df.apply(get_row_key,  axis=1)

In [13]:
pred_df[pred_df.taxon == 'agrostis stolonifera']['key'].values

array([], dtype=object)

In [14]:
eval_df[eval_df.taxon == 'agrostis stolonifera']['key'].values

array([], dtype=object)

In [15]:
eval_df[eval_df['key'].isin(pred_df['key'])]


# eval_df.to_csv('eval.csv')
# pred_df.to_csv('pred.csv')

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id,key
0,achillea millefolium,perennial,terrestrial,"herb, erect leafy/tussock, erect leafy","rhizome, solitary plant","rhizome, stem",0.40 m,1.00 m,"villose, glandular, bristly",NaN,...,NaN,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN,achillea millefolium|efloras.flora_of_china
1,achillea millefolium,perennial,terrestrial,"erect leafy/tussock, erect lealfy","rhizomatous, rhizome, stoloniferous, solitary ...","rhizome, stolon",0.06,0.65,"woolly, tomentose, glabrous",NaN,...,NaN,NaN,NaN,NaN,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN,achillea millefolium|efloras.flora_of_north_am...
3,andromeda polifolia,NaN,terrestrial,"creeping, geoxylices, scrambler",stoloniferous,"rootstock, tap root, stolon",0.05,0.8,hairy,NaN,...,1.0,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN,andromeda polifolia|efloras.flora_of_north_ame...
4,betula nana,NaN,terrestrial,"shrub, climber/scrambler, scrambler","solitary plant, stoloniferous","trunk, stolon",NaN,1 m,"glabrous, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,betula nana|efloras.flora_of_north_america
5,carex capillaris,NaN,terrestrial,erect leafy/tussock,rhizomematous,rhizome,0.60 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN,carex capillaris|efloras.flora_of_north_america
6,cuscuta epithymum,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,glandular,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,cuscuta epithymum|efloras.flora_of_pakistan
8,eleocharis palustris,perennial,terrestrial,"tussock, erect leafy, scrambler","rhizomatous, stoloniferous, solitary plant","rhizome, stolons, stem",0.1,0.95,"glabrous,pubescent",NaN,...,2.0,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,eleocharis palustris|ecoflora
10,hypochaeris radicata,perennial,terrestrial,"herb, erect leafy",solitary plant,"trunk, stem",0.15,0.6,ectzoochory,NaN,...,NaN,NaN,NaN,ectozoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN,hypochaeris radicata|efloras.flora_of_china
13,phalaris arundinacea,perennial,terrestrial,"erect leafy/tussock, scramblar","rhizome, stoloniferous",rhizome,0.6,2,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,phalaris arundinacea|ecoflora
14,rumex acetosa,perennial,terrestrial,"herb, geoxylices, erect leafy",solitary plant,"rootstock, stem",0.4,1,glabrous,NaN,...,2.5,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN,rumex acetosa|efloras.flora_of_china
16,salix reticulata,NaN,terrestrial,erect leafy,solitary plant,stem,0.03,0.15,"hairy, glabrescent, glandular, glabrous",NaN,...,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN,salix reticulata|efloras.flora_of_north_america
17,stellaria alsine,perennial,terrestrial,"scrambler, geoxylices",stoloniferous,"stolon, rootstock",NaN,NaN,"glabrous, ciliate",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,stellaria alsine|efloras.flora_of_pakistan
18,urtica dioica,perennial,terrestrial,"herb, erect leafy",solitary plant,stem,0.5,1.5,"hairy, ciliate, pubescent",NaN,...,1.5,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,urtica dioica|efloras.flora_of_pakistan
19,vaccinium myrtillus,perennial,terrestrial,"shrub, erect leafy tussock","solitary plant, rhizomatous, rhizome","trunk, rhizome",0.15,0.6,NaN,NaN,...,NaN,6.0,10.0,NaN,2n = 24,NaN,NaN,efloras.flora_of_china,NaN,vaccinium myrtillus|efloras.flora_of_china
20,valeriana dioica,NaN,terrestrial,"geoxylices, erect leafy","solitary plant, r","Rootstock , rhizome",0.11,0.38,"pilose, glabrous",NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,valeriana dioica|efloras.flora_of_pakistan

In [16]:
def normalise_value(column, value):
    """
    Normalise a trait value for comparison.
    """

    if pd.isna(value) or str(value).strip() == "":
        return None

    value = str(value).strip()

    # Dimensional/numeric fields, e.g.
    # plant min. height [m], seed max. length [mm]
    if re.search(r"\[[^\]]+\]", column):
        numbers = re.findall(r"-?\d+(?:\.\d+)?", value)

        if not numbers:
            return None

        return tuple(float(x) for x in numbers)

    # Categorical values:
    # treat comma-separated values as an unordered set
    return frozenset(
        x.strip().lower()
        for x in value.split(",")
        if x.strip()
    )


def compare_rows(pred, eval_, key):
    """
    Compare prediction and evaluation rows for a given key.
    Returns only fields whose normalised values differ.
    """

    pred_matches = pred.loc[pred["key"] == key]
    eval_matches = eval_.loc[eval_["key"] == key]

    if len(pred_matches) == 0:
        raise ValueError(f"No prediction found for key: {key}")

    if len(eval_matches) == 0:
        raise ValueError(f"No evaluation row found for key: {key}")

    pred_row = pred_matches.iloc[0]
    eval_row = eval_matches.iloc[0]

    differences = []

    columns = pred.columns.intersection(eval_.columns)

    for column in columns:
        if column == "key" or column.startswith("Unnamed:"):
            continue

        pred_value = pred_row[column]
        eval_value = eval_row[column]

        pred_norm = normalise_value(column, pred_value)
        eval_norm = normalise_value(column, eval_value)

        if pred_norm != eval_norm:
            differences.append({
                "field": column,
                "Pred": pred_value,
                "Eval": eval_value,
            })

    return pd.DataFrame(differences)

key = "agrostis stolonifera|efloras.flora_of_pakistan"

differences = compare_rows(pred_df, eval_df, key)

differences

ValueError: No prediction found for key: agrostis stolonifera|efloras.flora_of_pakistan

In [ ]:
def compare_all_rows(pred, eval_):
    """
    Compare all matching rows in pred and eval.
    Returns one row per differing trait, including taxon and key.
    """

    differences = []

    # Only compare records present in both datasets
    shared_keys = set(pred["key"]) & set(eval_["key"])

    for key in shared_keys:
        pred_row = pred.loc[pred["key"] == key].iloc[0]
        eval_row = eval_.loc[eval_["key"] == key].iloc[0]

        taxon = eval_row["taxon"]

        for column in pred.columns.intersection(eval_.columns):

            if column in {"key", "taxon", "source", "source_id"}:
                continue

            if column.startswith("Unnamed:"):
                continue

            pred_value = pred_row[column]
            eval_value = eval_row[column]

            pred_norm = normalise_value(column, pred_value)
            eval_norm = normalise_value(column, eval_value)

            if pred_norm != eval_norm:
                differences.append({
                    "taxon": taxon,
                    "key": key,
                    "field": column,
                    "Pred": pred_value,
                    "Eval": eval_value,
                })

    return pd.DataFrame(differences)

In [ ]:
differences = compare_all_rows(pred_df, eval_df)

differences.to_csv('validation-dataset-mismatches.csv')

In [ ]:
eval_df[eval_df.key.isin(pred_df['key'])]

In [ ]:
eval_df = eval_df.set_index('key')

In [ ]:
eval_df.to_csv('eval5.csv')

In [ ]:
eval_df

In [ ]:
pred_df = pred_df.set_index('key')

In [ ]:
pred_df.to_csv('pred5.csv')

In [ ]:
bhl_df = pd.read_excel(pred_xslx, sheet_name='bhl')

In [ ]:
bhl_df[bhl_df.taxon == 'Salix reticulata']

In [ ]:
combined = pd.read_excel(pred_xslx, sheet_name='combined')

In [ ]:
combined[~combined['fruit type'].isna()]['fruit type']

In [ ]:


eval_df[~eval_df['fruit type'].isna()]['fruit type']

In [ ]:
eval_df[eval_df.taxon == 'vaccinium myrtillus']

In [ ]:
eval_df[~eval_df['perennial organ'].isna()]

In [ ]:
row = pred_df[pred_df['taxon'] == 'alchemilla alpina'].iloc[0]
non_empty = row[
    row.notna() & row.astype(str).str.strip().ne("")
]

print(non_empty)

In [ ]:
row = eval_df[eval_df['taxon'] == 'alchemilla alpina'].iloc[0]
non_empty = row[
    row.notna() & row.astype(str).str.strip().ne("")
]

print(non_empty)

In [ ]:
bhl_df = pd.read_excel(pred_xslx, sheet_name='bhl')

bhl_df[(bhl_df.taxon == 'Eleocharis palustris') & (bhl_df.source_id ==11320960)].values