# Trait prediction vs evaluation comparison

This notebook compares a prediction CSV against an evaluation CSV.

It:

- matches records by `key`
- compares comma-separated categorical values as unordered sets
- normalises case and whitespace
- supports canonicalisation such as `cypselae` → `cypsela`
- compares dimensional values numerically
- converts compatible units such as `6 cm` → `0.06 m` for a `[m]` trait
- scores partial matches at the individual-value level
- calculates unmatched-value counts and accuracy by taxon/row
- calculates unmatched-value counts and accuracy by trait/column
- creates a side-by-side Excel sheet with columns such as `habit_pred` and `habit_eval`
- highlights both cells red when prediction and evaluation differ
- outputs detailed mismatches to a separate sheet

Empty/empty trait cells are excluded from accuracy calculations.

In [1]:
import re
from pathlib import Path

import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font
from openpyxl.utils import get_column_letter

In [2]:
DATA_DIR = Path('/Users/ben/Projects/ADEPT/Data')

OUTPUT_DIR = Path('/Users/ben/Projects/ADEPT/Code/PrePub/ADEPT/adept/data/processing/output')

ASSETS_DIR = Path('../adept/data/assets')

In [3]:
pred_file_path = OUTPUT_DIR / 'bhl/angiosperm-set123-54.bhl.traits.xlsx'
eval_file_path = DATA_DIR / 'ADEPT_eval_2309.xlsx'

eval_file_sheet_names=['set1', 'set2', 'set3']

In [4]:
traits_df = pd.read_parquet(ASSETS_DIR / 'traits.parquet')

In [5]:
eval_dfs = []

for sn in eval_file_sheet_names:
    eval_dfs.append(pd.read_excel(eval_file_path, sheet_name=sn))    
    
eval_df = pd.concat(eval_dfs)

# eval_df = pd.read_excel(eval_file_path, sheet_name=eval_file_sheet_name)
eval_df["taxon"] = eval_df["taxon"].astype("string").str.lower()

In [33]:
eval_df.to_csv(DATA_DIR / 'adept_trait_extraction_reference.csv', index=False)

In [7]:
unique_values = {}

for column in eval_df.columns:
    values = (
        eval_df[column]
        .dropna()
        .astype(str)
        .str.split(",")
        .explode()
        .str.strip()
    )
    unique_values[column] = sorted(values[values != ""].unique().tolist())

missing_chars = {}

all_chars = set(traits_df.character.unique())

for column, values in unique_values.items():

    if column in ['taxon', 'source', 'source_id', 'key'] or '[' in column: continue
    
    trait_chars = traits_df[traits_df['trait'] == column].character.unique()

    if trait_chars.any():

        difference = set(values) - set(trait_chars)
        if difference:
            missing_chars[column] = difference

    else:
        print(column)
        difference = set(values) - all_chars
        print(difference)
        


print(missing_chars)

life form
set()
calyx colour
set()
corolla colour
set()
corolla tube lipped
set()
stamen number
{'2.0', '4.0', '1.0', '5.0'}
stamenoid number
set()
carpel/ovary number
set()
heterostyly
set()
seeds per fruit min
set()
seeds per fruit max
{'2.0'}
seeds per fruit min.
{'2.0'}
ploidy level (2n)
{'120', '54', '2n = 14', '44', '2n = 8', '45', '12', '2n = 48', '2n=68', '2n = 54.', '28', '24', '2n = 38', '2n = 32', '40', '60', '2n = 18', '2n = 24', '100', '72', '2n = 22', '27', '30', '80', '36', '63', '2n = 16.', '58', '42', '56', '2n=32', '2n = 28'}
{}

In [8]:
eval_df["taxon"]

0              achillea millefolium
1              achillea millefolium
2                 alchemilla alpina
3               andromeda polifolia
4                       betula nana
5                  carex capillaris
6                 cuscuta epithymum
7                   drosera anglica
8              eleocharis palustris
9                   galium palustre
10             hypochaeris radicata
11                lythrum salicaria
12                   montia fontana
13             phalaris arundinacea
14                    rumex acetosa
15              rumex conglomeratus
16                 salix reticulata
17                 stellaria alsine
18                    urtica dioica
19              vaccinium myrtillus
20                 valeriana dioica
0              agrostis stolonifera
1                 aira caryophyllea
2                     ajuga reptans
3             anthoxanthum odoratum
4             arrhenatherum elatius
5                     berula erecta
6                  caltha palustris
7            campanula rotundifolia
8               cardamine pratensis
9                   centaurea nigra
10              cynosurus cristatus
11               alopecurus alpinus
12               ammophila arenaria
13                   bartsia alpina
14                  bellis perennis
15                      briza media
16               cardamine flexuosa
17    chrysosplenium oppositifolium
18                   cornus suecica
19            dactylorhiza maculata
0                digitalis purpurea
1                epilobium hirsutum
2                      erica vagans
3          eriophorum angustifolium
4              eriophorum vaginatum
5                    glaux maritima
6               gymnadenia conopsea
7                    holcus lanatus
8                     holcus mollis
9              hydrocotyle vulgaris
10                  mentha aquatica
11             myosotis scorpioides
12            pedicularis sylvatica
13              plantago lanceolata
Name: taxon, dtype: string

In [28]:

pred_df_list = []

for source, group_df in eval_df.groupby("source"):
    df = pd.read_excel(pred_file_path, sheet_name=source)

    df["taxon"] = df["taxon"].astype("string").str.lower()


    if source == 'bhl':

        matched_df = df.merge(
            group_df[["taxon", "source_id"]].drop_duplicates(),
            on=["taxon", "source_id"],
            how="inner"
        )

    else:

        matched_df = df[df.taxon.isin(group_df.taxon)]

    pred_df_list.append(matched_df)

pred_df = pd.concat(pred_df_list, ignore_index=True)

# pred_df.taxon

pred_df

,taxon,life form,habitat,habit,clonality,perennial organ,plant min. height [m],plant max. height [m],indumentum,spinescence,...,seed max. length [mm],seed min. diameter [mm],seed max. diameter [mm],dispersal mode,ploidy level (2n),root min. depth [cm],root max. depth [cm],source,source_id,matched_name
0,rumex conglomeratus,NaN,NaN,NaN,NaN,NaN,0.025 m,0.05 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,46694846.0,Rumex conglomeratus
1,mentha aquatica,perennial,terrestrial,erect leafy,"suckering, solitary plant",stem,NaN,NaN,pubescent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bhl,22883976.0,Mentha aquatica; Mentha sativa
2,plantago lanceolata,perennial,terrestrial,erect leafy,rhizomatous,rhizome,NaN,NaN,NaN,NaN,...,4 mm,NaN,NaN,NaN,"2n = 12, 24",NaN,NaN,bhl,7934546.0,Plantago lanceolata
3,eleocharis palustris,perennial,terrestrial,"tussock, erect leafy, caespitose, scrambler","stoloniferous, solitary plant, rhizomatous","stolon, stem, rhizome",0.10 m,0.95 m,NaN,NaN,...,2.0 mm,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,NaN
4,phalaris arundinacea,perennial,terrestrial,"erect leafy/tussock, scrambler","stoloniferous, rhizome","stolon, rhizome",0.60 m,2.00 m,glabrous,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
5,ajuga reptans,perennial,terrestrial,"erect leafy, erect leafy/tussock","stoloniferous, solitary plant, rhizome","stolon, stem, rhizome",0.10 m,0.30 m,"glabrescent, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
6,campanula rotundifolia,perennial,terrestrial,"erect leafy, geoxylices, erect leafy/tussock","solitary plant, rhizome","rootstock, stem, rhizome",0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,2n=68,NaN,NaN,ecoflora,NaN,NaN
7,alopecurus alpinus,perennial,terrestrial,"tussock, erect leafy/tussock, scrambler","stoloniferous, rhizomatous, rhizome","stolon, rhizome",0.10 m,0.45 m,"scabrous, glabrous",NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,NaN
8,ammophila arenaria,perennial,terrestrial,"erect leafy/tussock, scrambler","stoloniferous, rhizome","stolon, rhizome",0.50 m,1.20 m,pubescent,NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,NaN
9,bartsia alpina,perennial,terrestrial,erect leafy,solitary plant,stem,0.10 m,0.25 m,"glandular, pubescent",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
10,chrysosplenium oppositifolium,perennial,terrestrial,"herb, erect leafy",solitary plant,stem,0.05 m,0.15 m,"hairy, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
11,dactylorhiza maculata,perennial,terrestrial,"herb, erect leafy","solitary plant, tuber","stem, tuber",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
12,epilobium hirsutum,perennial,terrestrial,"herb, erect leafy","stoloniferous, solitary plant","stolon, stem",NaN,NaN,"hairy, ciliate",NaN,...,1 mm,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
13,holcus mollis,perennial,terrestrial,"tussock, erect leafy/tussock, scrambler","stoloniferous, rhizomatous","stolon, rhizome",0.20 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,ecoflora,NaN,NaN
14,hydrocotyle vulgaris,perennial,terrestrial,scrambler,stoloniferous,stolon,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecoflora,NaN,NaN
15,achillea millefolium,perennial,terrestrial,"herb, erect leafy, erect leafy/tussock","solitary plant, rhizome","stem, rhizome",0.40 m,1.00 m,"glandular, villous, villouse",NaN,...,2 mm,NaN,NaN,NaN,"2n = 18, 27, 36",NaN,NaN,efloras.flora_of_china,NaN,NaN
16,hypochaeris radicata,perennial,terrestrial,"herb, erect leafy, erect leavy",solitary plant,"stem, trunk",0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,ectozoochory,2n = 8,NaN,NaN,efloras.flora_of_china,NaN,NaN
17,rumex acetosa,perennial,terrestrial,"herb, erect leafy, geoxylices",solitary plant,"rootstock, stem",NaN,NaN,NaN,NaN,...,2 mm,NaN,NaN,NaN,2n = 14,NaN,NaN,efloras.flora_of_china,NaN,NaN
18,vaccinium myrtillus,perennial,terrestrial,"erect leafy/tussock, shrub","solitary plant, rhizomatous, rhizome","trunk, rhizome",0.15 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,2n = 24,NaN,NaN,efloras.flora_of_china,NaN,NaN
19,aira caryophyllea,NaN,terrestrial,"tussock, caespitose, erect leafy/tussock","solitary plant, rhizomatous",rhizome,0.05 m,0.30 m,NaN,NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,efloras.flora_of_china,NaN,NaN
20,anthoxanthum odoratum,NaN,terrestrial,"tussock, caespitose, erect leafy/tussock","rhizomatous, rhizome",rhizome,NaN,NaN,"pubescent, scabrous, glabrous",NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,efloras.flora_of_china,NaN,NaN
21,arrhenatherum elatius,NaN,terrestrial,erect leafy/tussock,NaN,rhizome,1 m,1.5 m,"scabrous, glabrous",NaN,...,NaN,NaN,NaN,ectozoochory,2n = 28,NaN,NaN,efloras.flora_of_china,NaN,NaN
22,berula erecta,hydrophyte,"aquatic, epiphyte, terrestrial","erect leafy, submerged",solitary plant,stem,0.40 m,1.00 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_china,NaN,NaN
23,cynosurus cristatus,perennial,terrestrial,"tussock, caespitose, erect leafy/tussock",rhizomatous,rhizome,NaN,NaN,glabrous,NaN,...,NaN,NaN,NaN,ectozoochory,2n = 14,NaN,NaN,efloras.flora_of_china,NaN,NaN
24,briza media,perennial,terrestrial,"tussock, caespitose, erect leafy/tussock","rhizomatous, rhizome",rhizome,NaN,NaN,"scabrous, glabrous",NaN,...,NaN,NaN,NaN,NaN,"2n = 14, 28",NaN,NaN,efloras.flora_of_china,NaN,NaN
25,digitalis purpurea,"annual, perennial",terrestrial,erect leafy,solitary plant,stem,0.60 m,1.20 m,NaN,NaN,...,NaN,NaN,NaN,anemochory,NaN,NaN,NaN,efloras.flora_of_china,NaN,NaN
26,gymnadenia conopsea,perennial,terrestrial,erect leafy,"solitary plant, tuber","stem, tuber",0.20 m,0.60 m,NaN,NaN,...,NaN,NaN,NaN,NaN,"2n = 30, 40, 42, 80, 100, 120",NaN,NaN,efloras.flora_of_china,NaN,NaN
27,achillea millefolium,perennial,terrestrial,"stoloniferous, erect leafy/tussock, erect leafy","stoloniferous, solitary plant, rhizomatous, rh...","stolon, stem, rhizome",0.06 m,0.65 m,"tomentose, woolly, glabrous",NaN,...,NaN,NaN,NaN,anemochory,"2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,efloras.flora_of_north_america,NaN,NaN
28,alchemilla alpina,NaN,terrestrial,erect leafy,solitary plant,stem,0.05 m,0.20 m,"sericeous, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
29,andromeda polifolia,NaN,terrestrial,"geoxylices, scrambler",stoloniferous,"rootstock, stolon",0.05 m,0.80 m,pubescent,NaN,...,1 mm,NaN,NaN,NaN,2n = 48,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
30,betula nana,NaN,terrestrial,"tree/shrub, climber/scrambler, shrub, scrambler","stoloniferous, solitary plant","stolon, trunk",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
31,carex capillaris,NaN,terrestrial,erect leafy/tussock,NaN,rhizome,0.60 m,0.60 m,NaN,NaN,...,1.7 mm,NaN,NaN,NaN,2n = 54.,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
32,salix reticulata,perennial,terrestrial,"erect leafy, tree",solitary plant,"stem, stipe",0.03 m,0.15 m,"sericeous, glabrous, glabrescent, pubescent, g...",NaN,...,NaN,NaN,NaN,NaN,2n = 38,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
33,caltha palustris,NaN,terrestrial,"erect leafy, climber/scrambler",solitary plant,"stolon, stem",NaN,NaN,NaN,NaN,...,2.5 mm,NaN,NaN,NaN,"2n=32, 56, 60",NaN,NaN,efloras.flora_of_north_america,NaN,NaN
34,cardamine pratensis,perennial,terrestrial,"erect leafy, erect leafy/tussock","solitary plant, rhizome","stem, rhizome",NaN,NaN,NaN,NaN,...,2 mm,NaN,NaN,NaN,2n = 16.,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
35,centaurea nigra,perennial,terrestrial,erect leafy,solitary plant,stem,0.30 m,1.50 m,NaN,NaN,...,NaN,NaN,NaN,ectozoochory,"2n = 22, 44",NaN,NaN,efloras.flora_of_north_america,NaN,NaN
36,bellis perennis,perennial,terrestrial,"herb, erect leafy/tussock",rhizome,rhizome,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,anemochory,2n = 18,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
37,cardamine flexuosa,"annual, perennial",terrestrial,"erect leafy, erect leafy/tussock","solitary plant, rhizome","stem, rhizome",NaN,NaN,NaN,NaN,...,1.5 mm,NaN,NaN,NaN,2n = 32,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
38,cornus suecica,perennial,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,hairy,NaN,...,NaN,NaN,NaN,ectozoochory,2n = 22,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
39,erica vagans,NaN,NaN,NaN,NaN,NaN,0.30 m,0.60 m,"glabrous, ciliate",NaN,...,0.6 mm,NaN,NaN,ectozoochory,2n = 24,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
40,eriophorum angustifolium,perennial,terrestrial,"erect leafy/tussock, scrambler","stoloniferous, rhizome","stolon, rhizome",NaN,NaN,NaN,NaN,...,5 mm,NaN,NaN,ectozoochory,NaN,NaN,NaN,efloras.flora_of_north_america,NaN,NaN
41,eriophorum vaginatum,NaN,terrestrial,"tussock, erect leafy/tussock","solitary plant, rhizomatous",rhizome,NaN,NaN,NaN,NaN,...,3.5 mm,NaN,NaN,ectozoochory,"2n = 58, 60",NaN,NaN,efloras.flora_of_north_america,NaN,NaN
42,cuscuta epithymum,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
43,galium palustre,NaN,terrestrial,erect leafy,solitary plant,stem,NaN,NaN,"scabrous, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
44,lythrum salicaria,perennial,NaN,NaN,NaN,NaN,0.40 m,0.70 m,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
45,stellaria alsine,perennial,terrestrial,"erect leafy, geoxylices, scrambler","stoloniferous, solitary plant","rootstock, stolon, stem",NaN,NaN,"ciliate, glabrous",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
46,urtica dioica,perennial,terrestrial,"herb, erect leafy",solitary plant,stem,0.50 m,1.50 m,NaN,NaN,...,1.5 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
47,valeriana dioica,NaN,terrestrial,"erect leafy, geoxylices","solitary plant, rhizomatous","rootstock, rhizome",0.11 m,0.38 m,NaN,NaN,...,3 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
48,agrostis stolonifera,perennial,terrestrial,"tussock, stoloniferous, caespitose, erect leaf...","stoloniferous, rhizomatous","stolon, rhizome",NaN,NaN,glabrous,NaN,...,NaN,NaN,NaN,ectozoochory,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN
49,glaux maritima,perennial,terrestrial,"prostrate, erect leafy","stoloniferous, solitary plant","stolon, stem",NaN,NaN,glandular,NaN,...,1.2 mm,NaN,NaN,NaN,NaN,NaN,NaN,efloras.flora_of_pakistan,NaN,NaN

In [29]:
def get_row_key(row):
    parts = [row.taxon, row.source]
    source_id = row.get("source_id")
    
    if pd.notna(source_id):   
        parts.append(str(source_id))
    
    return '|'.join(parts)

eval_df['key'] = eval_df.apply(get_row_key,  axis=1)    
pred_df['key'] = pred_df.apply(get_row_key,  axis=1)

In [34]:
eval_df[eval_df['key'].isin(pred_df['key'])].to_csv(DATA_DIR / 'adept_trait_extraction_reference.csv', index=False)

pred_df.to_csv('evaluation_pred_dataset.csv', index=False)


# eval_df.to_csv(DATA_DIR / 'adept_trait_extraction_reference.csv', index=False)

In [12]:
eval_df['dispersal mode']

0              NaN
1       anemochory
2              NaN
3              NaN
4              NaN
5              NaN
6              NaN
7              NaN
8     ectozoochory
9              NaN
10    ectozoochory
11             NaN
12             NaN
13             NaN
14             NaN
15             NaN
16             NaN
17             NaN
18             NaN
19             NaN
20             NaN
0     ectozoochory
1     ectozoochory
2              NaN
3     ectozoochory
4     ectozoochory
5              NaN
6              NaN
7              NaN
8              NaN
9     ectozoochory
10    ectozoochory
11    ectozoochory
12    ectozoochory
13             NaN
14             NaN
15             NaN
16             NaN
17             NaN
18    ectozoochory
19             NaN
0              NaN
1              NaN
2              NaN
3     ectozoochory
4     ectozoochory
5              NaN
6              NaN
7              NaN
8     ectozoochory
9              NaN
10             NaN
11             NaN
12             NaN
13             NaN
Name: dispersal mode, dtype: object

## Settings

In [13]:
PRED_FILE = "pred5.csv"
EVAL_FILE = "eval5.csv"
OUTPUT_FILE = "trait_evaluation.xlsx"

KEY_COL = "key"
TAXON_COL = "taxon"

META_COLS = {
    "key",
    "taxon",
    "source",
    "source_id",
    "description",
    "text",
    "Unnamed: 0",
}

CANONICAL_MAP = {
    "cypselae": "cypsela",
}

UNIT_TO_METRES = {
    "mm": 0.001,
    "cm": 0.01,
    "m": 1.0,
}

## Load data

In [31]:
# pred_df = pd.read_csv(PRED_FILE)
# eval_df = pd.read_csv(EVAL_FILE)

shared_keys = set(pred_df[KEY_COL]) & set(eval_df[KEY_COL])

print(f"Prediction rows: {len(pred_df):,}")
print(f"Evaluation rows: {len(eval_df):,}")
print(f"Shared keys: {len(shared_keys):,}")
print(f"Pred-only keys: {len(set(pred_df[KEY_COL]) - set(eval_df[KEY_COL])):,}")
print(f"Eval-only keys: {len(set(eval_df[KEY_COL]) - set(pred_df[KEY_COL])):,}")

Prediction rows: 50
Evaluation rows: 55
Shared keys: 50
Pred-only keys: 0
Eval-only keys: 5

## Normalisation helpers

In [15]:
def is_empty(value):
    """Return True for blank/NaN values."""
    return pd.isna(value) or str(value).strip() == ""


def canonicalise_text(value):
    """Normalise one categorical trait value."""
    value = str(value).strip().lower()
    value = re.sub(r"\s+", " ", value)
    return CANONICAL_MAP.get(value, value)


def get_column_unit(column):
    """
    Extract a dimensional unit from a column name.

    Examples:
        plant min. height [m] -> m
        seed max. length [mm] -> mm
    """
    match = re.search(r"\[(mm|cm|m)\]", column.lower())
    return match.group(1) if match else None


def normalise_measurement(token, target_unit):
    """
    Convert measurements to the unit specified by the trait column.

    Examples for a [m] column:
        "0.06 m" -> {0.06}
        "0.06"   -> {0.06}
        "6 cm"   -> {0.06}
    """
    if is_empty(token):
        return set()

    token = str(token).strip().lower()
    numbers = re.findall(r"-?\d+(?:\.\d+)?", token)

    if not numbers:
        return set()

    unit_match = re.search(r"\b(mm|cm|m)\b", token)
    source_unit = unit_match.group(1) if unit_match else target_unit

    result = set()

    for number in numbers:
        number = float(number)
        metres = number * UNIT_TO_METRES[source_unit]
        converted = metres / UNIT_TO_METRES[target_unit]
        result.add(round(converted, 10))

    return result


def normalise_cell(column, value):
    """
    Convert a trait cell into a set of normalised individual values.

    Thus:
        "ovate, lanceolate" == "lanceolate, ovate"

    and in a [m] column:
        "6 cm" == "0.06"
    """
    if is_empty(value):
        return set()

    unit = get_column_unit(column)

    if unit:
        return normalise_measurement(value, unit)

    return {
        canonicalise_text(v)
        for v in str(value).split(",")
        if v.strip()
    }

## Create side-by-side prediction/evaluation table

In [16]:
def create_side_by_side_comparison(pred_df, eval_df):
    """
    Create one row per shared key with prediction and evaluation
    values next to each other for every trait.

    Example columns:
        habit_pred
        habit_eval
        clonality_pred
        clonality_eval

    Returns:
        comparison_df
        mismatches
        trait_cols
    """

    trait_cols = [
        col
        for col in pred_df.columns.intersection(eval_df.columns)
        if col not in META_COLS
        and not col.startswith("Unnamed:")
    ]

    pred_indexed = pred_df.set_index(KEY_COL, drop=False)
    eval_indexed = eval_df.set_index(KEY_COL, drop=False)

    shared_keys = [
        key
        for key in eval_df[KEY_COL]
        if key in pred_indexed.index
    ]

    rows = []
    mismatches = set()

    for key in shared_keys:
        pred_row = pred_indexed.loc[key]
        eval_row = eval_indexed.loc[key]

        if isinstance(pred_row, pd.DataFrame):
            pred_row = pred_row.iloc[0]

        if isinstance(eval_row, pd.DataFrame):
            eval_row = eval_row.iloc[0]

        result = {
            "taxon": eval_row.get("taxon", ""),
            "source": eval_row.get("source", ""),
            "key": key,
        }

        for trait in trait_cols:
            pred_value = pred_row.get(trait)
            eval_value = eval_row.get(trait)

            pred_col = f"{trait}_pred"
            eval_col = f"{trait}_eval"

            result[pred_col] = pred_value
            result[eval_col] = eval_value

            pred_norm = normalise_cell(trait, pred_value)
            eval_norm = normalise_cell(trait, eval_value)

            if pred_norm != eval_norm:
                mismatches.add((key, pred_col, eval_col))

        rows.append(result)

    return pd.DataFrame(rows), mismatches, trait_cols


comparison_df, comparison_mismatches, trait_cols = (
    create_side_by_side_comparison(pred_df, eval_df)
)

comparison_df.head()

,taxon,source,key,life form_pred,life form_eval,habitat_pred,habitat_eval,habit_pred,habit_eval,clonality_pred,...,seed max. diameter [mm]_pred,seed max. diameter [mm]_eval,dispersal mode_pred,dispersal mode_eval,ploidy level (2n)_pred,ploidy level (2n)_eval,root min. depth [cm]_pred,root min. depth [cm]_eval,root max. depth [cm]_pred,root max. depth [cm]_eval
0,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,perennial,perennial,terrestrial,terrestrial,"herb, erect leafy, erect leafy/tussock","herb, erect leafy/tussock, erect leafy","solitary plant, rhizome",...,NaN,NaN,NaN,NaN,"2n = 18, 27, 36","2n = 18, 27, 36",NaN,NaN,NaN,NaN
1,achillea millefolium,efloras.flora_of_north_america,achillea millefolium|efloras.flora_of_north_am...,perennial,perennial,terrestrial,terrestrial,"stoloniferous, erect leafy/tussock, erect leafy","erect leafy/tussock, erect leafy, stoloniferous","stoloniferous, solitary plant, rhizomatous, rh...",...,NaN,NaN,anemochory,anemochory,"2n = 18, 27, 36, 45, 54, 63, 72","2n = 18, 27, 36, 45, 54, 63, 72",NaN,NaN,NaN,NaN
2,alchemilla alpina,efloras.flora_of_north_america,alchemilla alpina|efloras.flora_of_north_america,NaN,NaN,terrestrial,terrestrial,erect leafy,erect leafy,solitary plant,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,andromeda polifolia,efloras.flora_of_north_america,andromeda polifolia|efloras.flora_of_north_ame...,NaN,NaN,terrestrial,terrestrial,"geoxylices, scrambler","geoxylices, scrambler",stoloniferous,...,NaN,NaN,NaN,NaN,2n = 48,2n = 48,NaN,NaN,NaN,NaN
4,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,NaN,NaN,terrestrial,terrestrial,"tree/shrub, climber/scrambler, shrub, scrambler","shrub, tree/shrub, climber/scrambler, scrambler","stoloniferous, solitary plant",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Calculate row, trait and detailed mismatch summaries

In [17]:
def evaluate_traits(pred_df, eval_df, trait_cols):
    """
    Compare every individual trait value for all shared rows.

    Value accuracy:
        matched / (matched + extra predicted + missed eval)

    Empty/empty trait cells are ignored.
    """

    pred_indexed = pred_df.set_index(KEY_COL, drop=False)
    eval_indexed = eval_df.set_index(KEY_COL, drop=False)

    shared_keys = [
        key
        for key in eval_df[KEY_COL]
        if key in pred_indexed.index
    ]

    row_results = []
    differences = []

    trait_totals = {
        trait: {
            "matched": 0,
            "extra_pred": 0,
            "missed_eval": 0,
            "exact_cells": 0,
            "different_cells": 0,
            "populated_cells": 0,
        }
        for trait in trait_cols
    }

    for key in shared_keys:
        pred_row = pred_indexed.loc[key]
        eval_row = eval_indexed.loc[key]

        if isinstance(pred_row, pd.DataFrame):
            pred_row = pred_row.iloc[0]

        if isinstance(eval_row, pd.DataFrame):
            eval_row = eval_row.iloc[0]

        taxon = eval_row.get(TAXON_COL, key)
        source = eval_row.get("source", "")

        row_matched = 0
        row_extra = 0
        row_missed = 0
        exact_trait_cells = 0
        different_trait_cells = 0
        populated_trait_cells = 0

        for trait in trait_cols:
            pred_raw = pred_row.get(trait)
            eval_raw = eval_row.get(trait)

            pred_values = normalise_cell(trait, pred_raw)
            eval_values = normalise_cell(trait, eval_raw)

            if not pred_values and not eval_values:
                continue

            populated_trait_cells += 1
            trait_totals[trait]["populated_cells"] += 1

            matched = pred_values & eval_values
            extra_pred = pred_values - eval_values
            missed_eval = eval_values - pred_values

            n_matched = len(matched)
            n_extra = len(extra_pred)
            n_missed = len(missed_eval)

            row_matched += n_matched
            row_extra += n_extra
            row_missed += n_missed

            trait_totals[trait]["matched"] += n_matched
            trait_totals[trait]["extra_pred"] += n_extra
            trait_totals[trait]["missed_eval"] += n_missed

            if pred_values == eval_values:
                exact_trait_cells += 1
                trait_totals[trait]["exact_cells"] += 1
            else:
                different_trait_cells += 1
                trait_totals[trait]["different_cells"] += 1

                differences.append({
                    "taxon": taxon,
                    "source": source,
                    "key": key,
                    "trait": trait,
                    "Pred": pred_raw,
                    "Eval": eval_raw,
                    "matched values": ", ".join(map(str, sorted(matched))),
                    "extra predicted values": ", ".join(
                        map(str, sorted(extra_pred))
                    ),
                    "missed eval values": ", ".join(
                        map(str, sorted(missed_eval))
                    ),
                    "matched count": n_matched,
                    "extra pred count": n_extra,
                    "missed eval count": n_missed,
                })

        unmatched = row_extra + row_missed
        total_union = row_matched + unmatched

        value_accuracy = (
            100 * row_matched / total_union
            if total_union
            else 100.0
        )

        cell_accuracy = (
            100 * exact_trait_cells / populated_trait_cells
            if populated_trait_cells
            else 100.0
        )

        row_results.append({
            "taxon": taxon,
            "source": source,
            "key": key,
            "matched values": row_matched,
            "extra predicted values": row_extra,
            "missed eval values": row_missed,
            "unmatched values": unmatched,
            "total values": total_union,
            "value accuracy %": value_accuracy,
            "exact trait cells": exact_trait_cells,
            "different trait cells": different_trait_cells,
            "populated trait cells": populated_trait_cells,
            "trait cell accuracy %": cell_accuracy,
        })

    trait_results = []

    for trait, counts in trait_totals.items():
        if counts["populated_cells"] == 0:
            continue

        matched = counts["matched"]
        extra = counts["extra_pred"]
        missed = counts["missed_eval"]
        unmatched = extra + missed
        total = matched + unmatched

        value_accuracy = (
            100 * matched / total
            if total
            else 100.0
        )

        cell_accuracy = (
            100 * counts["exact_cells"] / counts["populated_cells"]
        )

        trait_results.append({
            "trait": trait,
            "matched values": matched,
            "extra predicted values": extra,
            "missed eval values": missed,
            "unmatched values": unmatched,
            "total values": total,
            "value accuracy %": value_accuracy,
            "exact cells": counts["exact_cells"],
            "different cells": counts["different_cells"],
            "populated cells": counts["populated_cells"],
            "trait cell accuracy %": cell_accuracy,
        })

    return (
        pd.DataFrame(row_results),
        pd.DataFrame(trait_results),
        pd.DataFrame(differences),
    )


row_summary, trait_summary, differences = evaluate_traits(
    pred_df,
    eval_df,
    trait_cols,
)

## Row-level summary

In [18]:
row_summary.sort_values(
    "value accuracy %"
).reset_index(drop=True)

,taxon,source,key,matched values,extra predicted values,missed eval values,unmatched values,total values,value accuracy %,exact trait cells,different trait cells,populated trait cells,trait cell accuracy %
0,cardamine flexuosa,efloras.flora_of_north_america,cardamine flexuosa|efloras.flora_of_north_america,18,10,18,28,46,39.130435,8,19,27,29.629630
1,eriophorum vaginatum,efloras.flora_of_north_america,eriophorum vaginatum|efloras.flora_of_north_am...,11,6,11,17,28,39.285714,8,13,21,38.095238
2,urtica dioica,efloras.flora_of_pakistan,urtica dioica|efloras.flora_of_pakistan,15,2,19,21,36,41.666667,12,13,25,48.000000
3,plantago lanceolata,bhl,plantago lanceolata|bhl|7934546.0,15,8,8,16,31,48.387097,9,15,24,37.500000
4,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,13,2,7,9,22,59.090909,13,8,21,61.904762
5,berula erecta,efloras.flora_of_china,berula erecta|efloras.flora_of_china,13,0,9,9,22,59.090909,10,8,18,55.555556
6,erica vagans,efloras.flora_of_north_america,erica vagans|efloras.flora_of_north_america,22,6,7,13,35,62.857143,19,11,30,63.333333
7,cardamine pratensis,efloras.flora_of_north_america,cardamine pratensis|efloras.flora_of_north_ame...,26,2,12,14,40,65.000000,21,6,27,77.777778
8,eriophorum angustifolium,efloras.flora_of_north_america,eriophorum angustifolium|efloras.flora_of_nort...,19,1,9,10,29,65.517241,13,10,23,56.521739
9,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,27,5,9,14,41,65.853659,15,9,24,62.500000
10,phalaris arundinacea,ecoflora,phalaris arundinacea|ecoflora,12,0,6,6,18,66.666667,9,5,14,64.285714
11,bellis perennis,efloras.flora_of_north_america,bellis perennis|efloras.flora_of_north_america,14,6,1,7,21,66.666667,11,6,17,64.705882
12,holcus mollis,ecoflora,holcus mollis|ecoflora,18,1,8,9,27,66.666667,14,5,19,73.684211
13,briza media,efloras.flora_of_china,briza media|efloras.flora_of_china,15,2,5,7,22,68.181818,10,6,16,62.500000
14,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,16,5,2,7,23,69.565217,10,6,16,62.500000
15,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,18,2,5,7,25,72.000000,7,5,12,58.333333
16,hydrocotyle vulgaris,ecoflora,hydrocotyle vulgaris|ecoflora,13,2,3,5,18,72.222222,10,5,15,66.666667
17,cornus suecica,efloras.flora_of_north_america,cornus suecica|efloras.flora_of_north_america,24,3,6,9,33,72.727273,21,8,29,72.413793
18,rumex conglomeratus,bhl,rumex conglomeratus|bhl|46694846.0,11,2,2,4,15,73.333333,8,2,10,80.000000
19,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,20,1,6,7,27,74.074074,13,7,20,65.000000
20,centaurea nigra,efloras.flora_of_north_america,centaurea nigra|efloras.flora_of_north_america,28,4,5,9,37,75.675676,18,5,23,78.260870
21,rumex acetosa,efloras.flora_of_china,rumex acetosa|efloras.flora_of_china,29,3,6,9,38,76.315789,21,7,28,75.000000
22,alchemilla alpina,efloras.flora_of_north_america,alchemilla alpina|efloras.flora_of_north_america,17,2,3,5,22,77.272727,10,3,13,76.923077
23,digitalis purpurea,efloras.flora_of_china,digitalis purpurea|efloras.flora_of_china,24,3,4,7,31,77.419355,18,5,23,78.260870
24,arrhenatherum elatius,efloras.flora_of_china,arrhenatherum elatius|efloras.flora_of_china,14,0,4,4,18,77.777778,12,3,15,80.000000
25,bartsia alpina,ecoflora,bartsia alpina|ecoflora,22,2,4,6,28,78.571429,20,5,25,80.000000
26,salix reticulata,efloras.flora_of_north_america,salix reticulata|efloras.flora_of_north_america,33,8,1,9,42,78.571429,16,7,23,69.565217
27,aira caryophyllea,efloras.flora_of_china,aira caryophyllea|efloras.flora_of_china,16,0,4,4,20,80.000000,11,2,13,84.615385
28,gymnadenia conopsea,efloras.flora_of_china,gymnadenia conopsea|efloras.flora_of_china,26,5,1,6,32,81.250000,16,5,21,76.190476
29,mentha aquatica,bhl,mentha aquatica|bhl|22883976.0,18,1,3,4,22,81.818182,10,3,13,76.923077
30,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,27,4,2,6,33,81.818182,18,5,23,78.260870
31,epilobium hirsutum,ecoflora,epilobium hirsutum|ecoflora,31,3,3,6,37,83.783784,22,5,27,81.481481
32,eleocharis palustris,ecoflora,eleocharis palustris|ecoflora,22,1,3,4,26,84.615385,14,3,17,82.352941
33,ammophila arenaria,ecoflora,ammophila arenaria|ecoflora,17,0,3,3,20,85.000000,14,1,15,93.333333
34,agrostis stolonifera,efloras.flora_of_pakistan,agrostis stolonifera|efloras.flora_of_pakistan,17,0,3,3,20,85.000000,12,1,13,92.307692
35,alopecurus alpinus,ecoflora,alopecurus alpinus|ecoflora,21,1,2,3,24,87.500000,15,2,17,88.235294
36,anthoxanthum odoratum,efloras.flora_of_china,anthoxanthum odoratum|efloras.flora_of_china,21,0,3,3,24,87.500000,15,1,16,93.750000
37,cynosurus cristatus,efloras.flora_of_china,cynosurus cristatus|efloras.flora_of_china,15,0,2,2,17,88.235294,13,2,15,86.666667
38,stellaria alsine,efloras.flora_of_pakistan,stellaria alsine|efloras.flora_of_pakistan,23,3,0,3,26,88.461538,14,3,17,82.352941
39,cuscuta epithymum,efloras.flora_of_pakistan,cuscuta epithymum|efloras.flora_of_pakistan,16,0,2,2,18,88.888889,15,2,17,88.235294
40,caltha palustris,efloras.flora_of_north_america,caltha palustris|efloras.flora_of_north_america,27,1,2,3,30,90.000000,14,3,17,82.352941
41,dactylorhiza maculata,ecoflora,dactylorhiza maculata|ecoflora,19,2,0,2,21,90.476190,11,2,13,84.615385
42,andromeda polifolia,efloras.flora_of_north_america,andromeda polifolia|efloras.flora_of_north_ame...,23,2,0,2,25,92.000000,20,2,22,90.909091
43,campanula rotundifolia,ecoflora,campanula rotundifolia|ecoflora,40,1,2,3,43,93.023256,26,2,28,92.857143
44,ajuga reptans,ecoflora,ajuga reptans|ecoflora,29,0,2,2,31,93.548387,18,2,20,90.000000
45,valeriana dioica,efloras.flora_of_pakistan,valeriana dioica|efloras.flora_of_pakistan,29,0,2,2,31,93.548387,18,2,20,90.000000
46,glaux maritima,efloras.flora_of_pakistan,glaux maritima|efloras.flora_of_pakistan,30,2,0,2,32,93.750000,22,2,24,91.666667
47,vaccinium myrtillus,efloras.flora_of_china,vaccinium myrtillus|efloras.flora_of_china,33,1,1,2,35,94.285714,22,2,24,91.666667
48,chrysosplenium oppositifolium,ecoflora,chrysosplenium oppositifolium|ecoflora,26,1,0,1,27,96.296296,17,1,18,94.444444
49,achillea millefolium,efloras.flora_of_north_america,achillea millefolium|efloras.flora_of_north_am...,45,0,1,1,46,97.826087,23,1,24,95.833333

## Trait-level summary

In [19]:
trait_summary.sort_values(
    "value accuracy %"
).reset_index(drop=True)

,trait,matched values,extra predicted values,missed eval values,unmatched values,total values,value accuracy %,exact cells,different cells,populated cells,trait cell accuracy %
0,seeds per fruit min.,0,0,1,1,1,0.0,0,1,1,0.0
1,seed min. diameter [mm],0,0,1,1,1,0.0,0,1,1,0.0
2,reproduction architecture,0,2,0,2,2,0.0,0,2,2,0.0
3,seeds per fruit max,0,0,1,1,1,0.0,0,1,1,0.0
4,flower shape,0,0,2,2,2,0.0,0,2,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...
58,flower orientation,5,0,0,0,5,100.0,5,0,5,100.0
59,flower symmetry,1,0,0,0,1,100.0,1,0,1,100.0
60,inflorescence orientation,5,0,0,0,5,100.0,5,0,5,100.0
61,leaf arrangement,5,0,0,0,5,100.0,5,0,5,100.0
62,reward,2,0,0,0,2,100.0,2,0,2,100.0

## Detailed differences

In [20]:
differences.head(50)

,taxon,source,key,trait,Pred,Eval,matched values,extra predicted values,missed eval values,matched count,extra pred count,missed eval count
0,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,indumentum,"glandular, villous, villouse","glandular, bristly",glandular,"villous, villouse",bristly,1,2,1
1,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,leaf architecture,"pinnatisect, pinnatipartite",pinnatisect,pinnatisect,pinnatipartite,,1,1,0
2,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,leaf apex,"attenuate, lanceolate",attenuate,attenuate,lanceolate,,1,1,0
3,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,inflorescence arrangement,NaN,"panicle, capitulum",,,"capitulum, panicle",0,0,2
4,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,flower shape,NaN,tubulate,,,tubulate,0,0,1
5,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,flower colour,NaN,"white, pink, purple",,,"pink, purple, white",0,0,3
6,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,fruit type,NaN,achene,,,achene,0,0,1
7,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,seed min. width [mm],NaN,2.0,,,2.0,0,0,1
8,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,seed max. length [mm],2 mm,NaN,,2.0,,0,1,0
9,achillea millefolium,efloras.flora_of_north_america,achillea millefolium|efloras.flora_of_north_am...,fruit type,NaN,cypsela,,,cypsela,0,0,1
10,alchemilla alpina,efloras.flora_of_north_america,alchemilla alpina|efloras.flora_of_north_america,indumentum,"sericeous, glabrous","hairy, sericeous, glabrous, pubescent","glabrous, sericeous",,"hairy, pubescent",2,0,2
11,alchemilla alpina,efloras.flora_of_north_america,alchemilla alpina|efloras.flora_of_north_america,leaf shape,"orbicular, orbiculate, elliptic, oblanceolate,...","orbicular, elliptic, spatulate","elliptic, orbicular, spatulate","oblanceolate, orbiculate",,3,2,0
12,alchemilla alpina,efloras.flora_of_north_america,alchemilla alpina|efloras.flora_of_north_america,fruit type,NaN,achene,,,achene,0,0,1
13,andromeda polifolia,efloras.flora_of_north_america,andromeda polifolia|efloras.flora_of_north_ame...,fruit structure,dry,NaN,,dry,,0,1,0
14,andromeda polifolia,efloras.flora_of_north_america,andromeda polifolia|efloras.flora_of_north_ame...,fruit dehiscence,dehiscent,NaN,,dehiscent,,0,1,0
15,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,plant max. height [m],NaN,1 m,,,1.0,0,0,1
16,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,indumentum,NaN,"glabrous, pubescent",,,"glabrous, pubescent",0,0,2
17,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,leaf shape,"rounded, orbicular, cordate, orbiculate, obova...","orbicular, orbiculate, obovate, reniform","obovate, orbicular, orbiculate, reniform","cordate, rounded",,4,2,0
18,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,flower sex,NaN,staminate,,,staminate,0,0,1
19,betula nana,efloras.flora_of_north_america,betula nana|efloras.flora_of_north_america,fruit type,NaN,samara,,,samara,0,0,1
20,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,clonality,NaN,rhizomatous,,,rhizomatous,0,0,1
21,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,inflorescence arrangement,NaN,spike,,,spike,0,0,1
22,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,flower sex,NaN,staminate,,,staminate,0,0,1
23,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,fruit type,NaN,achene,,,achene,0,0,1
24,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,fruit shape,NaN,obovoid,,,obovoid,0,0,1
25,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,seed min. length [mm],1.2 mm,NaN,,1.2,,0,1,0
26,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,seed max. length [mm],1.7 mm,1.2,,1.7,1.2,0,1,1
27,carex capillaris,efloras.flora_of_north_america,carex capillaris|efloras.flora_of_north_america,seed min. diameter [mm],NaN,1.7,,,1.7,0,0,1
28,cuscuta epithymum,efloras.flora_of_pakistan,cuscuta epithymum|efloras.flora_of_pakistan,indumentum,NaN,glandular,,,glandular,0,0,1
29,cuscuta epithymum,efloras.flora_of_pakistan,cuscuta epithymum|efloras.flora_of_pakistan,petal fusion,NaN,fusion,,,fusion,0,0,1
30,eleocharis palustris,ecoflora,eleocharis palustris|ecoflora,indumentum,NaN,"glabrous, pubescent",,,"glabrous, pubescent",0,0,2
31,eleocharis palustris,ecoflora,eleocharis palustris|ecoflora,flower architecture,naked,NaN,,naked,,0,1,0
32,eleocharis palustris,ecoflora,eleocharis palustris|ecoflora,fruit type,NaN,nut,,,nut,0,0,1
33,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,plant min. height [m],NaN,0.5,,,0.5,0,0,1
34,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,plant max. height [m],NaN,0.8,,,0.8,0,0,1
35,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,indumentum,"scabrous, glabrous","scabrous, glabrous, papillose","glabrous, scabrous",,papillose,2,0,1
36,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,leaf position,NaN,whorled,,,whorled,0,0,1
37,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,leaf shape,lanceolate,"lanceolate, linear",lanceolate,,linear,1,0,1
38,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,leaf apex,"acute, recurved, cuspidate","cuspidate, acute","acute, cuspidate",recurved,,2,1,0
39,galium palustre,efloras.flora_of_pakistan,galium palustre|efloras.flora_of_pakistan,inflorescence arrangement,NaN,panicle,,,panicle,0,0,1
40,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,habit,"herb, erect leafy, erect leavy","herb, erect leafy","erect leafy, herb",erect leavy,,2,1,0
41,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,leaf shape,"oblanceolate, rounded, spatulate, orbicular","spatulate, oblanceolate","oblanceolate, spatulate","orbicular, rounded",,2,2,0
42,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,leaf base,"attenuate, rounded",attenuate,attenuate,rounded,,1,1,0
43,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,inflorescence arrangement,capitulum,"corymb, capitulum",capitulum,,corymb,1,0,1
44,hypochaeris radicata,efloras.flora_of_china,hypochaeris radicata|efloras.flora_of_china,fruit type,NaN,achene,,,achene,0,0,1
45,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,leaf shape,"elliptic, ovate, cordate, lanceolate","ovate, elliptic, lanceolate,","elliptic, lanceolate, ovate",cordate,,3,1,0
46,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,leaf apex,"acuminate, attenuate, acute, lanceolate","acuminate, acute,","acuminate, acute","attenuate, lanceolate",,2,2,0
47,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,leaf base,amplexicaul,"amplexicaul, cordate",amplexicaul,,cordate,1,0,1
48,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,inflorescence arrangement,NaN,spike,,,spike,0,0,1
49,lythrum salicaria,efloras.flora_of_pakistan,lythrum salicaria|efloras.flora_of_pakistan,fruit structure,dry,NaN,,dry,,0,1,0

## Overall precision, recall and F1

In [21]:
matched = row_summary["matched values"].sum()
extra = row_summary["extra predicted values"].sum()
missed = row_summary["missed eval values"].sum()

precision = matched / (matched + extra) if (matched + extra) else 0
recall = matched / (matched + missed) if (matched + missed) else 0
f1 = (
    2 * precision * recall / (precision + recall)
    if (precision + recall)
    else 0
)

print(f"Matched values: {matched:,}")
print(f"Extra predicted values: {extra:,}")
print(f"Missed eval values: {missed:,}")
print(f"Precision: {precision:.1%}")
print(f"Recall: {recall:.1%}")
print(f"F1: {f1:.1%}")

Matched values: 1,078
Extra predicted values: 116
Missed eval values: 221
Precision: 90.3%
Recall: 83.0%
F1: 86.5%

## Write Excel workbook

In [22]:
def format_worksheet(ws):
    """Apply simple readable formatting to a worksheet."""

    header_fill = PatternFill(
        fill_type="solid",
        fgColor="D9EAF7",
    )
    header_font = Font(bold=True)

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    for cell in ws[1]:
        cell.fill = header_fill
        cell.font = header_font

    for column_cells in ws.columns:
        column_letter = get_column_letter(column_cells[0].column)

        max_length = 0

        for cell in column_cells:
            if cell.value is not None:
                max_length = max(
                    max_length,
                    len(str(cell.value)),
                )

        ws.column_dimensions[column_letter].width = min(
            max(max_length + 2, 10),
            45,
        )


def create_excel_report(
    comparison_df,
    comparison_mismatches,
    row_summary,
    trait_summary,
    differences,
    output_file,
):
    """
    Write the full Excel comparison workbook.

    Sheets:
      - Side by side
      - Row summary
      - Trait summary
      - Differences
    """

    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        comparison_df.to_excel(
            writer,
            sheet_name="Side by side",
            index=False,
        )

        row_summary.to_excel(
            writer,
            sheet_name="Row summary",
            index=False,
        )

        trait_summary.to_excel(
            writer,
            sheet_name="Trait summary",
            index=False,
        )

        differences.to_excel(
            writer,
            sheet_name="Differences",
            index=False,
        )

    wb = load_workbook(output_file)

    red_fill = PatternFill(
        fill_type="solid",
        fgColor="FFC7CE",
    )
    red_font = Font(color="9C0006")

    ws = wb["Side by side"]

    headers = {
        cell.value: cell.column
        for cell in ws[1]
    }

    key_column = headers[KEY_COL]

    key_to_row = {}

    for excel_row in range(2, ws.max_row + 1):
        key = ws.cell(
            row=excel_row,
            column=key_column,
        ).value

        key_to_row[key] = excel_row

    for key, pred_col, eval_col in comparison_mismatches:
        if key not in key_to_row:
            continue

        row_number = key_to_row[key]

        for column_name in (pred_col, eval_col):
            if column_name not in headers:
                continue

            cell = ws.cell(
                row=row_number,
                column=headers[column_name],
            )

            cell.fill = red_fill
            cell.font = red_font

    for ws in wb.worksheets:
        format_worksheet(ws)

    for sheet_name in ["Row summary", "Trait summary"]:
        ws = wb[sheet_name]

        for header_cell in ws[1]:
            if "%" in str(header_cell.value):
                for row in range(2, ws.max_row + 1):
                    ws.cell(
                        row=row,
                        column=header_cell.column,
                    ).number_format = "0.0"

    wb.save(output_file)


create_excel_report(
    comparison_df=comparison_df,
    comparison_mismatches=comparison_mismatches,
    row_summary=row_summary,
    trait_summary=trait_summary,
    differences=differences,
    output_file=OUTPUT_FILE,
)

print(f"Excel report written to: {Path(OUTPUT_FILE).resolve()}")

Excel report written to: /Users/ben/Projects/ADEPT/Code/PrePub/ADEPT/notebooks/trait_evaluation.xlsx

## Optional: inspect the worst-performing taxa

In [23]:
row_summary[
    [
        "taxon",
        "source",
        "unmatched values",
        "value accuracy %",
        "trait cell accuracy %",
    ]
].sort_values(
    "value accuracy %"
).reset_index(drop=True)

,taxon,source,unmatched values,value accuracy %,trait cell accuracy %
0,cardamine flexuosa,efloras.flora_of_north_america,28,39.130435,29.629630
1,eriophorum vaginatum,efloras.flora_of_north_america,17,39.285714,38.095238
2,urtica dioica,efloras.flora_of_pakistan,21,41.666667,48.000000
3,plantago lanceolata,bhl,16,48.387097,37.500000
4,carex capillaris,efloras.flora_of_north_america,9,59.090909,61.904762
5,berula erecta,efloras.flora_of_china,9,59.090909,55.555556
6,erica vagans,efloras.flora_of_north_america,13,62.857143,63.333333
7,cardamine pratensis,efloras.flora_of_north_america,14,65.000000,77.777778
8,eriophorum angustifolium,efloras.flora_of_north_america,10,65.517241,56.521739
9,achillea millefolium,efloras.flora_of_china,14,65.853659,62.500000
10,phalaris arundinacea,ecoflora,6,66.666667,64.285714
11,bellis perennis,efloras.flora_of_north_america,7,66.666667,64.705882
12,holcus mollis,ecoflora,9,66.666667,73.684211
13,briza media,efloras.flora_of_china,7,68.181818,62.500000
14,lythrum salicaria,efloras.flora_of_pakistan,7,69.565217,62.500000
15,betula nana,efloras.flora_of_north_america,7,72.000000,58.333333
16,hydrocotyle vulgaris,ecoflora,5,72.222222,66.666667
17,cornus suecica,efloras.flora_of_north_america,9,72.727273,72.413793
18,rumex conglomeratus,bhl,4,73.333333,80.000000
19,galium palustre,efloras.flora_of_pakistan,7,74.074074,65.000000
20,centaurea nigra,efloras.flora_of_north_america,9,75.675676,78.260870
21,rumex acetosa,efloras.flora_of_china,9,76.315789,75.000000
22,alchemilla alpina,efloras.flora_of_north_america,5,77.272727,76.923077
23,digitalis purpurea,efloras.flora_of_china,7,77.419355,78.260870
24,arrhenatherum elatius,efloras.flora_of_china,4,77.777778,80.000000
25,bartsia alpina,ecoflora,6,78.571429,80.000000
26,salix reticulata,efloras.flora_of_north_america,9,78.571429,69.565217
27,aira caryophyllea,efloras.flora_of_china,4,80.000000,84.615385
28,gymnadenia conopsea,efloras.flora_of_china,6,81.250000,76.190476
29,mentha aquatica,bhl,4,81.818182,76.923077
30,hypochaeris radicata,efloras.flora_of_china,6,81.818182,78.260870
31,epilobium hirsutum,ecoflora,6,83.783784,81.481481
32,eleocharis palustris,ecoflora,4,84.615385,82.352941
33,ammophila arenaria,ecoflora,3,85.000000,93.333333
34,agrostis stolonifera,efloras.flora_of_pakistan,3,85.000000,92.307692
35,alopecurus alpinus,ecoflora,3,87.500000,88.235294
36,anthoxanthum odoratum,efloras.flora_of_china,3,87.500000,93.750000
37,cynosurus cristatus,efloras.flora_of_china,2,88.235294,86.666667
38,stellaria alsine,efloras.flora_of_pakistan,3,88.461538,82.352941
39,cuscuta epithymum,efloras.flora_of_pakistan,2,88.888889,88.235294
40,caltha palustris,efloras.flora_of_north_america,3,90.000000,82.352941
41,dactylorhiza maculata,ecoflora,2,90.476190,84.615385
42,andromeda polifolia,efloras.flora_of_north_america,2,92.000000,90.909091
43,campanula rotundifolia,ecoflora,3,93.023256,92.857143
44,ajuga reptans,ecoflora,2,93.548387,90.000000
45,valeriana dioica,efloras.flora_of_pakistan,2,93.548387,90.000000
46,glaux maritima,efloras.flora_of_pakistan,2,93.750000,91.666667
47,vaccinium myrtillus,efloras.flora_of_china,2,94.285714,91.666667
48,chrysosplenium oppositifolium,ecoflora,1,96.296296,94.444444
49,achillea millefolium,efloras.flora_of_north_america,1,97.826087,95.833333

## Optional: inspect the worst-performing traits

In [24]:
trait_summary[
    [
        "trait",
        "unmatched values",
        "extra predicted values",
        "missed eval values",
        "value accuracy %",
        "trait cell accuracy %",
    ]
].sort_values(
    "value accuracy %"
).reset_index(drop=True)

,trait,unmatched values,extra predicted values,missed eval values,value accuracy %,trait cell accuracy %
0,seeds per fruit min.,1,0,1,0.0,0.0
1,seed min. diameter [mm],1,0,1,0.0,0.0
2,reproduction architecture,2,2,0,0.0,0.0
3,seeds per fruit max,1,0,1,0.0,0.0
4,flower shape,2,0,2,0.0,0.0
...,...,...,...,...,...,...
58,flower orientation,0,0,0,100.0,100.0
59,flower symmetry,0,0,0,100.0,100.0
60,inflorescence orientation,0,0,0,100.0,100.0
61,leaf arrangement,0,0,0,100.0,100.0
62,reward,0,0,0,100.0,100.0

## Optional: inspect differences for one taxon

In [25]:
taxon_search = "Achillea millefolium"

differences[
    differences["taxon"].str.contains(
        taxon_search,
        case=False,
        na=False,
    )
].reset_index(drop=True)

,taxon,source,key,trait,Pred,Eval,matched values,extra predicted values,missed eval values,matched count,extra pred count,missed eval count
0,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,indumentum,"glandular, villous, villouse","glandular, bristly",glandular,"villous, villouse",bristly,1,2,1
1,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,leaf architecture,"pinnatisect, pinnatipartite",pinnatisect,pinnatisect,pinnatipartite,,1,1,0
2,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,leaf apex,"attenuate, lanceolate",attenuate,attenuate,lanceolate,,1,1,0
3,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,inflorescence arrangement,NaN,"panicle, capitulum",,,"capitulum, panicle",0,0,2
4,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,flower shape,NaN,tubulate,,,tubulate,0,0,1
5,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,flower colour,NaN,"white, pink, purple",,,"pink, purple, white",0,0,3
6,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,fruit type,NaN,achene,,,achene,0,0,1
7,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,seed min. width [mm],NaN,2.0,,,2.0,0,0,1
8,achillea millefolium,efloras.flora_of_china,achillea millefolium|efloras.flora_of_china,seed max. length [mm],2 mm,NaN,,2.0,,0,1,0
9,achillea millefolium,efloras.flora_of_north_america,achillea millefolium|efloras.flora_of_north_am...,fruit type,NaN,cypsela,,,cypsela,0,0,1